import type { Topic, TopicQuestion } from '@/lib/content/schema'

export const topics: Topic[] = [
  {
    id: 'topic-statistics-metrics',
    name: 'Statistics & Metrics',
    order: 1,
    summary:
      'Explain which metric a problem deserves, why accuracy is usually the wrong one, and how to tell whether an online result is real.',
  },
  {
    id: 'topic-classical-ml',
    name: 'Classical ML',
    order: 2,
    summary:
      'Derive logistic regression and tree ensembles from first principles and defend a model choice against a neural network.',
  },
  {
    id: 'topic-deep-learning',
    name: 'Deep Learning Fundamentals',
    order: 3,
    summary:
      'Explain how a network learns via backprop and optimizers, and diagnose why a model refuses to train.',
  },
  {
    id: 'topic-embeddings',
    name: 'Embeddings & Retrieval',
    order: 4,
    summary:
      'Explain how embeddings are trained and indexed, and defend chunking and hybrid retrieval choices with their trade-offs.',
  },
  {
    id: 'topic-transformers',
    name: 'Transformer Architecture',
    order: 5,
    summary:
      'Walk through a transformer block from tokenization to output, and justify every architectural choice against its alternative.',
  },
  {
    id: 'topic-llm-pretraining',
    name: 'LLM Pretraining',
    order: 6,
    summary:
      'Explain how a base model is pretrained at scale, from the objective to the parallelism strategy that fits it on hardware.',
  },
  {
    id: 'topic-fine-tuning',
    name: 'Fine-Tuning & Alignment',
    order: 7,
    summary:
      'Compare SFT, LoRA, RLHF, and DPO, and defend when fine-tuning is the wrong tool next to RAG or prompting.',
  },
  {
    id: 'topic-inference',
    name: 'LLM Inference & Serving',
    order: 8,
    summary:
      'Explain the mechanics of autoregressive decoding and defend a serving architecture on throughput, latency, and cost.',
  },
  {
    id: 'topic-rag-evaluation',
    name: 'RAG & Evaluation',
    order: 9,
    summary:
      'Diagnose why a RAG system hallucinates or retrieves poorly, and defend the retrieval and generation metrics used to prove it.',
  },
  {
    id: 'topic-agents-safety',
    name: 'Agents & Safety',
    order: 10,
    summary:
      'Explain how an agent plans, uses tools, and is evaluated, and defend the guardrails that keep it from causing harm.',
  },
]

export const topicQuestions: TopicQuestion[] = [
  // topic-statistics-metrics
  { id: 'q-statistics-metrics-why-not-accuracy', topicId: 'topic-statistics-metrics',
    text: 'Why is accuracy the wrong metric under class imbalance, and what would you use instead?', minutes: 10 },
  { id: 'q-statistics-metrics-precision-vs-recall', topicId: 'topic-statistics-metrics',
    text: 'When does precision matter more than recall, and when is it the other way round?', minutes: 10 },
  { id: 'q-statistics-metrics-f1-vs-fbeta', topicId: 'topic-statistics-metrics',
    text: 'How does F-beta generalize F1, and how do you choose beta for a given business cost?', minutes: 10 },
  { id: 'q-statistics-metrics-roc-vs-pr-auc', topicId: 'topic-statistics-metrics',
    text: 'When is PR-AUC the right choice over ROC-AUC, and why does ROC-AUC mislead under imbalance?', minutes: 10 },
  { id: 'q-statistics-metrics-calibration', topicId: 'topic-statistics-metrics',
    text: 'What does it mean for a classifier to be calibrated, and how would you measure and fix miscalibration?', minutes: 10 },
  { id: 'q-statistics-metrics-decision-threshold', topicId: 'topic-statistics-metrics',
    text: 'How do you pick a decision threshold for a classifier instead of defaulting to 0.5?', minutes: 10 },
  { id: 'q-statistics-metrics-confidence-interval', topicId: 'topic-statistics-metrics',
    text: 'How do you put a confidence interval on a metric like accuracy or CTR, and what does the interval width tell you?', minutes: 10 },
  { id: 'q-statistics-metrics-p-value', topicId: 'topic-statistics-metrics',
    text: 'What is a p-value, and what common misinterpretation of it should you avoid?', minutes: 10 },
  { id: 'q-statistics-metrics-ab-test-sizing', topicId: 'topic-statistics-metrics',
    text: 'How do you size an A/B test, and what goes wrong if you skip the power calculation?', minutes: 10 },
  { id: 'q-statistics-metrics-novelty-effect', topicId: 'topic-statistics-metrics',
    text: 'What is a novelty effect in an A/B test, and how do you detect and control for it?', minutes: 10 },
  { id: 'q-statistics-metrics-interference', topicId: 'topic-statistics-metrics',
    text: 'What is interference between arms in an experiment, and how does it bias your results?', minutes: 10 },
  { id: 'q-statistics-metrics-offline-online-gap', topicId: 'topic-statistics-metrics',
    text: 'Why might offline metric gains fail to show up in an online A/B test?', minutes: 10 },

  // topic-classical-ml
  { id: 'q-classical-ml-logistic-regression', topicId: 'topic-classical-ml',
    text: 'Derive logistic regression from its loss function up: what is being optimized, and why is the loss convex?', minutes: 10 },
  { id: 'q-classical-ml-tree-splits', topicId: 'topic-classical-ml',
    text: 'Why do decision trees split on information gain or Gini impurity, and how do the two differ?', minutes: 10 },
  { id: 'q-classical-ml-rf-vs-gbm', topicId: 'topic-classical-ml',
    text: 'How do random forests and gradient boosting differ in how they combine trees, and what does each trade off?', minutes: 10 },
  { id: 'q-classical-ml-xgboost', topicId: 'topic-classical-ml',
    text: 'What does XGBoost add on top of plain gradient boosting that makes it faster and more accurate?', minutes: 10 },
  { id: 'q-classical-ml-bias-variance', topicId: 'topic-classical-ml',
    text: 'Explain the bias-variance trade-off and how you would diagnose which one is hurting a model.', minutes: 10 },
  { id: 'q-classical-ml-l1-vs-l2', topicId: 'topic-classical-ml',
    text: 'How do L1 and L2 regularization differ in their effect on model weights, and when would you pick one over the other?', minutes: 10 },
  { id: 'q-classical-ml-cross-validation-leakage', topicId: 'topic-classical-ml',
    text: 'What leakage traps commonly break cross-validation, and how do you design folds to avoid them?', minutes: 10 },
  { id: 'q-classical-ml-data-leakage', topicId: 'topic-classical-ml',
    text: 'What is data leakage, give a concrete example, and how do you prevent it in a training pipeline?', minutes: 10 },
  { id: 'q-classical-ml-class-imbalance', topicId: 'topic-classical-ml',
    text: 'What are the trade-offs between resampling, class weighting, and threshold tuning for handling class imbalance?', minutes: 10 },
  { id: 'q-classical-ml-feature-engineering', topicId: 'topic-classical-ml',
    text: 'What feature engineering techniques matter most for tabular data, and why do they still beat raw features for tree models?', minutes: 10 },
  { id: 'q-classical-ml-kmeans-pca', topicId: 'topic-classical-ml',
    text: 'In two sentences each, explain what k-means and PCA optimize and how they differ in purpose.', minutes: 10 },
  { id: 'q-classical-ml-linear-vs-nn', topicId: 'topic-classical-ml',
    text: 'When would you choose a linear model over a neural network, even if the network scores higher offline?', minutes: 10 },

  // topic-deep-learning
  { id: 'q-deep-learning-backprop', topicId: 'topic-deep-learning',
    text: 'Explain backpropagation in words: how does the chain rule turn a loss into a gradient for every weight?', minutes: 10 },
  { id: 'q-deep-learning-sgd-adam-adamw', topicId: 'topic-deep-learning',
    text: 'How do SGD, Adam, and AdamW differ, and why did AdamW become the default for training transformers?', minutes: 10 },
  { id: 'q-deep-learning-warmup-cosine-decay', topicId: 'topic-deep-learning',
    text: 'Why do we use learning rate warmup followed by cosine decay instead of a constant learning rate?', minutes: 10 },
  { id: 'q-deep-learning-batchnorm-vs-layernorm', topicId: 'topic-deep-learning',
    text: 'How do BatchNorm and LayerNorm differ in what they normalize over, and why do transformers use LayerNorm?', minutes: 10 },
  { id: 'q-deep-learning-dropout', topicId: 'topic-deep-learning',
    text: 'How does dropout regularize a network, and why is it turned off at inference time?', minutes: 10 },
  { id: 'q-deep-learning-residual-connections', topicId: 'topic-deep-learning',
    text: 'Why do residual connections let you train much deeper networks than you could otherwise?', minutes: 10 },
  { id: 'q-deep-learning-vanishing-exploding-gradients', topicId: 'topic-deep-learning',
    text: 'What causes vanishing and exploding gradients, and what architectural or training fixes address each?', minutes: 10 },
  { id: 'q-deep-learning-gradient-clipping', topicId: 'topic-deep-learning',
    text: 'What does gradient clipping do mechanically, and when would you reach for it during training?', minutes: 10 },
  { id: 'q-deep-learning-mixed-precision', topicId: 'topic-deep-learning',
    text: "How do FP16 and BF16 differ for training, and why does FP16 training need loss scaling while BF16 usually doesn't?", minutes: 10 },
  { id: 'q-deep-learning-cnn-rnn-attention', topicId: 'topic-deep-learning',
    text: 'In one line each, what problem does a CNN, an RNN, and attention solve that makes each suited to different data?', minutes: 10 },
  { id: 'q-deep-learning-overfitting-signals', topicId: 'topic-deep-learning',
    text: 'What signals in a training curve tell you a model is overfitting rather than still learning?', minutes: 10 },
  { id: 'q-deep-learning-debug-not-training', topicId: 'topic-deep-learning',
    text: "Your model's loss will not go down at all: walk through how you would debug it.", minutes: 10 },

  // topic-embeddings
  { id: 'q-embeddings-what-is-an-embedding', topicId: 'topic-embeddings',
    text: 'What is an embedding, and what property must the embedding space have for similarity search to work?', minutes: 10 },
  { id: 'q-embeddings-cosine-vs-dot-vs-euclidean', topicId: 'topic-embeddings',
    text: 'How do cosine similarity, dot product, and Euclidean distance differ as similarity measures, and when does the choice matter?', minutes: 10 },
  { id: 'q-embeddings-bi-encoder-vs-cross-encoder', topicId: 'topic-embeddings',
    text: 'How do bi-encoders and cross-encoders differ in architecture, and why is one used for retrieval and the other for reranking?', minutes: 10 },
  { id: 'q-embeddings-contrastive-training', topicId: 'topic-embeddings',
    text: 'How does contrastive training produce a useful embedding space, and what role do positive and negative pairs play?', minutes: 10 },
  { id: 'q-embeddings-mteb-limits', topicId: 'topic-embeddings',
    text: 'What does the MTEB benchmark measure, and what are its limits when picking an embedding model for your own data?', minutes: 10 },
  { id: 'q-embeddings-chunking-effect', topicId: 'topic-embeddings',
    text: 'How does chunk size and boundary choice affect retrieval quality, and what failure modes come from chunking too coarse or too fine?', minutes: 10 },
  { id: 'q-embeddings-hnsw', topicId: 'topic-embeddings',
    text: 'How does HNSW organize vectors to make approximate nearest-neighbor search fast, and what does it trade off for that speed?', minutes: 10 },
  { id: 'q-embeddings-ivf', topicId: 'topic-embeddings',
    text: 'How does an IVF index partition the vector space, and how does the nprobe parameter trade recall for latency?', minutes: 10 },
  { id: 'q-embeddings-recall-latency-tradeoff', topicId: 'topic-embeddings',
    text: 'In an ANN index, how do you trade recall against latency, and what parameters control that trade-off?', minutes: 10 },
  { id: 'q-embeddings-sparse-vs-dense-hybrid', topicId: 'topic-embeddings',
    text: 'Why does hybrid retrieval combining BM25 and dense embeddings usually beat either alone?', minutes: 10 },
  { id: 'q-embeddings-hard-negatives', topicId: 'topic-embeddings',
    text: 'What are hard negatives in embedding training, and why do they improve the model more than random negatives?', minutes: 10 },
  { id: 'q-embeddings-dimensionality-tradeoff', topicId: 'topic-embeddings',
    text: 'How do you trade off embedding dimensionality against retrieval quality and storage or serving cost?', minutes: 10 },

  // topic-transformers
  { id: 'q-transformers-tokenization-bpe', topicId: 'topic-transformers',
    text: 'How does byte-pair encoding build a vocabulary, and why do LLMs tokenize subwords instead of whole words or characters?', minutes: 10 },
  { id: 'q-transformers-why-attention', topicId: 'topic-transformers',
    text: 'What problem does attention solve that made it replace RNNs for sequence modeling?', minutes: 10 },
  { id: 'q-transformers-qkv', topicId: 'topic-transformers',
    text: 'What are query, key, and value in self-attention, and what role does each play in computing the output?', minutes: 10 },
  { id: 'q-transformers-why-scale-by-sqrt-d', topicId: 'topic-transformers',
    text: 'Why do we scale attention scores by the square root of the head dimension before the softmax?', minutes: 10 },
  { id: 'q-transformers-causal-masking', topicId: 'topic-transformers',
    text: 'What does causal masking do in a decoder, and why is it necessary for autoregressive generation?', minutes: 10 },
  { id: 'q-transformers-multi-head-attention', topicId: 'topic-transformers',
    text: 'Why use multiple attention heads instead of one large head, and what tends to differ across the heads that emerge?', minutes: 10 },
  { id: 'q-transformers-positional-encoding', topicId: 'topic-transformers',
    text: 'How does RoPE differ from learned and sinusoidal positional embeddings, and why did most modern models switch to RoPE?', minutes: 10 },
  { id: 'q-transformers-pre-norm-vs-post-norm', topicId: 'topic-transformers',
    text: 'How does pre-norm differ from post-norm placement of the residual and normalization in a transformer block, and why do most large models use pre-norm?', minutes: 10 },
  { id: 'q-transformers-layernorm-vs-rmsnorm', topicId: 'topic-transformers',
    text: 'How does RMSNorm differ from LayerNorm, and why do many recent LLMs prefer it?', minutes: 10 },
  { id: 'q-transformers-mlp-gelu-swiglu', topicId: 'topic-transformers',
    text: "What does the transformer's MLP block do, and why did SwiGLU replace GELU in many modern architectures?", minutes: 10 },
  { id: 'q-transformers-mha-vs-mqa-vs-gqa', topicId: 'topic-transformers',
    text: 'How do MHA, MQA, and GQA differ in how they share key and value heads, and what does each trade off?', minutes: 10 },
  { id: 'q-transformers-mixture-of-experts', topicId: 'topic-transformers',
    text: 'In two paragraphs, how does a mixture-of-experts layer route tokens to experts, and what does it buy you over a dense feedforward layer?', minutes: 10 },
  { id: 'q-transformers-counting-parameters', topicId: 'topic-transformers',
    text: "How would you estimate a transformer's parameter count given its layer count, hidden size, and vocabulary size?", minutes: 10 },
  { id: 'q-transformers-memory-in-bf16', topicId: 'topic-transformers',
    text: "How much memory does it take to hold a model's weights in BF16, and how does that change once you add optimizer state for training?", minutes: 10 },

  // topic-llm-pretraining
  { id: 'q-llm-pretraining-next-token-prediction', topicId: 'topic-llm-pretraining',
    text: 'What is the next-token prediction objective, and why is cross-entropy the natural loss for it?', minutes: 10 },
  { id: 'q-llm-pretraining-perplexity', topicId: 'topic-llm-pretraining',
    text: 'What is perplexity, and what does a perplexity of 20 tell you about a model?', minutes: 10 },
  { id: 'q-llm-pretraining-scaling-laws-chinchilla', topicId: 'topic-llm-pretraining',
    text: 'What did the Chinchilla paper show about the relationship between model size, data size, and compute-optimal training?', minutes: 10 },
  { id: 'q-llm-pretraining-data-mixture-dedup', topicId: 'topic-llm-pretraining',
    text: 'Why does the data mixture and deduplication strategy matter as much as the architecture for pretraining quality?', minutes: 10 },
  { id: 'q-llm-pretraining-adamw-weight-decay', topicId: 'topic-llm-pretraining',
    text: 'Why is AdamW preferred for pretraining, and what does weight decay actually do to the learned weights?', minutes: 10 },
  { id: 'q-llm-pretraining-instabilities', topicId: 'topic-llm-pretraining',
    text: 'What causes training instabilities like loss spikes at scale, and what fixes are commonly used to recover from or prevent them?', minutes: 10 },
  { id: 'q-llm-pretraining-lr-schedules-at-scale', topicId: 'topic-llm-pretraining',
    text: 'How do learning rate schedules used at pretraining scale differ from those in typical fine-tuning, and why?', minutes: 10 },
  { id: 'q-llm-pretraining-parallelism-strategies', topicId: 'topic-llm-pretraining',
    text: 'How do data parallelism, FSDP, tensor parallelism, and pipeline parallelism each shard the training job, and when do you combine them?', minutes: 10 },
  { id: 'q-llm-pretraining-all-reduce', topicId: 'topic-llm-pretraining',
    text: 'What does an all-reduce operation do during distributed training, and where does it become a bottleneck?', minutes: 10 },
  { id: 'q-llm-pretraining-gradient-checkpointing', topicId: 'topic-llm-pretraining',
    text: 'How does gradient checkpointing trade compute for memory during training?', minutes: 10 },
  { id: 'q-llm-pretraining-flops-6nd', topicId: 'topic-llm-pretraining',
    text: 'How does the 6ND approximation estimate training FLOPs, and what do N and D represent?', minutes: 10 },
  { id: 'q-llm-pretraining-70b-single-gpu', topicId: 'topic-llm-pretraining',
    text: "Why doesn't a 70B-parameter model fit on a single GPU, even accounting for quantization?", minutes: 10 },

  // topic-fine-tuning
  { id: 'q-fine-tuning-sft-instruction-tuning', topicId: 'topic-fine-tuning',
    text: "What does supervised fine-tuning for instruction following change about a base model's behavior?", minutes: 10 },
  { id: 'q-fine-tuning-lora', topicId: 'topic-fine-tuning',
    text: "How does LoRA reduce the number of trainable parameters, and why does it still recover most of full fine-tuning's quality?", minutes: 10 },
  { id: 'q-fine-tuning-qlora', topicId: 'topic-fine-tuning',
    text: 'What does QLoRA add on top of LoRA, and why does it let you fine-tune much larger models on limited GPU memory?', minutes: 10 },
  { id: 'q-fine-tuning-full-vs-lora-tradeoffs', topicId: 'topic-fine-tuning',
    text: 'What do you give up by choosing LoRA over full fine-tuning, and when is that trade-off not worth it?', minutes: 10 },
  { id: 'q-fine-tuning-catastrophic-forgetting', topicId: 'topic-fine-tuning',
    text: 'What is catastrophic forgetting during fine-tuning, and how would you detect and mitigate it?', minutes: 10 },
  { id: 'q-fine-tuning-rlhf-pipeline', topicId: 'topic-fine-tuning',
    text: 'Walk through the RLHF pipeline: how does a reward model get trained, and how does PPO use it to update the policy?', minutes: 10 },
  { id: 'q-fine-tuning-dpo-vs-ppo', topicId: 'topic-fine-tuning',
    text: 'How does DPO avoid training a separate reward model, and why did it replace PPO for many teams?', minutes: 10 },
  { id: 'q-fine-tuning-preference-data-quality', topicId: 'topic-fine-tuning',
    text: 'What makes preference data high quality for RLHF or DPO, and how does noisy preference data hurt the result?', minutes: 10 },
  { id: 'q-fine-tuning-rag-vs-ft-vs-prompting', topicId: 'topic-fine-tuning',
    text: 'Walk through a decision framework for choosing between RAG, fine-tuning, and prompting for a given problem.', minutes: 10 },
  { id: 'q-fine-tuning-when-it-hurts', topicId: 'topic-fine-tuning',
    text: 'In what situations does fine-tuning make a model worse, and how would you catch that before shipping?', minutes: 10 },
  { id: 'q-fine-tuning-synthetic-data-for-sft', topicId: 'topic-fine-tuning',
    text: 'When and how would you use synthetic data for SFT, and what quality risks does it introduce?', minutes: 10 },
  { id: 'q-fine-tuning-evaluating-beyond-loss', topicId: 'topic-fine-tuning',
    text: 'Why is training loss insufficient to evaluate a fine-tune, and what would you measure instead?', minutes: 10 },

  // topic-inference
  { id: 'q-inference-autoregressive-decoding', topicId: 'topic-inference',
    text: "How does autoregressive decoding generate a sequence one token at a time, and why can't it be trivially parallelized?", minutes: 10 },
  { id: 'q-inference-prefill-vs-decode', topicId: 'topic-inference',
    text: 'How do the prefill and decode phases of LLM inference differ in their compute characteristics?', minutes: 10 },
  { id: 'q-inference-kv-cache', topicId: 'topic-inference',
    text: 'What does the KV cache store, and how do you derive its memory size formula from model dimensions and sequence length?', minutes: 10 },
  { id: 'q-inference-decode-memory-bound', topicId: 'topic-inference',
    text: 'Why is the decode phase memory-bandwidth bound rather than compute bound, and what does that imply for batching?', minutes: 10 },
  { id: 'q-inference-static-vs-continuous-batching', topicId: 'topic-inference',
    text: 'How does continuous batching improve on static batching for serving throughput?', minutes: 10 },
  { id: 'q-inference-paged-attention', topicId: 'topic-inference',
    text: 'How does PagedAttention manage the KV cache, and what problem in naive KV cache allocation does it solve?', minutes: 10 },
  { id: 'q-inference-flash-attention', topicId: 'topic-inference',
    text: 'In one paragraph, how does FlashAttention speed up attention without changing its output?', minutes: 10 },
  { id: 'q-inference-quantization', topicId: 'topic-inference',
    text: 'How do FP16, BF16, INT8, and INT4 differ in what they cost you in model quality versus memory and speed?', minutes: 10 },
  { id: 'q-inference-speculative-decoding', topicId: 'topic-inference',
    text: 'How does speculative decoding use a draft model to speed up generation from a larger target model?', minutes: 10 },
  { id: 'q-inference-throughput-latency-cost', topicId: 'topic-inference',
    text: 'How do throughput, latency, and cost per token trade off against each other when you tune batch size?', minutes: 10 },
  { id: 'q-inference-sizing-serving-fleet', topicId: 'topic-inference',
    text: 'How would you size a serving fleet to support N concurrent users at a target latency?', minutes: 10 },
  { id: 'q-inference-streaming-ttft', topicId: 'topic-inference',
    text: 'What is time to first token, and how does streaming change the user-perceived latency of a response?', minutes: 10 },

  // topic-rag-evaluation
  { id: 'q-rag-evaluation-chunking-overlap', topicId: 'topic-rag-evaluation',
    text: 'How do chunking strategy and chunk overlap affect what a retriever can find, and how do you choose both?', minutes: 10 },
  { id: 'q-rag-evaluation-hybrid-rrf', topicId: 'topic-rag-evaluation',
    text: 'How does reciprocal rank fusion combine BM25 and dense retrieval rankings into one result list?', minutes: 10 },
  { id: 'q-rag-evaluation-reranking', topicId: 'topic-rag-evaluation',
    text: "What does a reranker add after initial retrieval, and why can't you just retrieve more candidates with the first-stage retriever instead?", minutes: 10 },
  { id: 'q-rag-evaluation-query-rewriting-hyde-multiquery', topicId: 'topic-rag-evaluation',
    text: "How do query rewriting, HyDE, and multi-query each try to close the gap between a user's question and how the answer is phrased in the corpus?", minutes: 10 },
  { id: 'q-rag-evaluation-context-budgeting-lost-in-middle', topicId: 'topic-rag-evaluation',
    text: "What is the 'lost in the middle' effect, and how does it change how you budget and order context in a prompt?", minutes: 10 },
  { id: 'q-rag-evaluation-citations-attribution', topicId: 'topic-rag-evaluation',
    text: 'How do you generate an answer with citations that reliably attribute claims to their source passages?', minutes: 10 },
  { id: 'q-rag-evaluation-retrieval-metrics', topicId: 'topic-rag-evaluation',
    text: 'How do Recall@k, MRR, and NDCG differ as retrieval metrics, and when would you report one over another?', minutes: 10 },
  { id: 'q-rag-evaluation-generation-metrics-llm-judge', topicId: 'topic-rag-evaluation',
    text: 'How do you measure faithfulness and relevance of a generated answer, and what biases does an LLM-as-judge setup introduce?', minutes: 10 },
  { id: 'q-rag-evaluation-gold-eval-set', topicId: 'topic-rag-evaluation',
    text: 'What makes a gold evaluation set for RAG trustworthy, and how do you build one without leaking test data into retrieval?', minutes: 10 },
  { id: 'q-rag-evaluation-why-rag-hallucinates', topicId: 'topic-rag-evaluation',
    text: 'What are the distinct causes of hallucination in a RAG system, and what is the fix for each one?', minutes: 10 },
  { id: 'q-rag-evaluation-semantic-caching', topicId: 'topic-rag-evaluation',
    text: 'How does semantic caching reduce cost and latency in a RAG system, and what correctness risk does it introduce?', minutes: 10 },
  { id: 'q-rag-evaluation-prompt-injection-via-retrieval', topicId: 'topic-rag-evaluation',
    text: 'How can retrieved content carry a prompt injection attack, and how would you defend against it?', minutes: 10 },

  // topic-agents-safety
  { id: 'q-agents-safety-tool-use-function-calling', topicId: 'topic-agents-safety',
    text: 'How does function calling let an LLM invoke external tools, and what has to be true about the schema for it to work reliably?', minutes: 10 },
  { id: 'q-agents-safety-react-loop', topicId: 'topic-agents-safety',
    text: 'How does the ReAct loop interleave reasoning and acting, and why does that improve over reasoning alone?', minutes: 10 },
  { id: 'q-agents-safety-planning-vs-reactive', topicId: 'topic-agents-safety',
    text: 'How do planning agents differ from purely reactive agents, and what failure modes does each avoid or introduce?', minutes: 10 },
  { id: 'q-agents-safety-memory-types', topicId: 'topic-agents-safety',
    text: 'How do short-term, long-term, and episodic memory differ in an agent system, and what does each get used for?', minutes: 10 },
  { id: 'q-agents-safety-orchestration-patterns', topicId: 'topic-agents-safety',
    text: 'What are the differences between chaining, routing, parallelization, orchestrator-workers, and evaluator-optimizer as multi-agent orchestration patterns?', minutes: 10 },
  { id: 'q-agents-safety-human-in-the-loop', topicId: 'topic-agents-safety',
    text: 'How would you design a human-in-the-loop approval flow for an agent that can take irreversible actions?', minutes: 10 },
  { id: 'q-agents-safety-agent-evaluation', topicId: 'topic-agents-safety',
    text: "How do you evaluate an agent along task success, cost, steps, and safety, and why isn't task success alone enough?", minutes: 10 },
  { id: 'q-agents-safety-guardrails-levels', topicId: 'topic-agents-safety',
    text: 'How do input, output, and action-level guardrails differ in what they catch, and why do you need all three?', minutes: 10 },
  { id: 'q-agents-safety-prompt-injection-jailbreaks', topicId: 'topic-agents-safety',
    text: 'What defenses would you put in place against prompt injection and jailbreak attempts on an agent?', minutes: 10 },
  { id: 'q-agents-safety-cost-controls', topicId: 'topic-agents-safety',
    text: 'How do budgets, caching, and model routing work together to control the cost of an agent system in production?', minutes: 10 },
  { id: 'q-agents-safety-observability', topicId: 'topic-agents-safety',
    text: 'What do traces, spans, and token accounting give you when debugging an agent, and how would you use them to find a failure?', minutes: 10 },
  { id: 'q-agents-safety-failure-modes', topicId: 'topic-agents-safety',
    text: 'What are common agent failure modes like infinite loops, tool misuse, and over-permissioning, and how do you guard against each?', minutes: 10 },
]
