import type { CsQuestion, CsTopic } from '@/lib/content/schema'

// CS fundamentals bank. This is the round separate from DSA and system design.
//
// Amazon runs it as an explicit gated round of roughly 30-40 minutes over OS, DBMS and
// networking; Meta runs a comparable short OS/Linux/networking screen on the Production
// Engineer track and expects Linux internals plus real troubleshooting fluency. Google
// and general SWE loops fold a subset (concurrency, caching, walking through a URL)
// into other rounds rather than a dedicated quiz, so those questions carry no company tag.
//
// `companies` is tagged only where the research supports it: Amazon on OS + DBMS +
// networking, Meta on OS + networking + Linux internals (not databases). Everything else
// is deliberately `[]` rather than guessed at.
//
// Every `answer` is written the way you would say it out loud in the room - the mechanism
// and the consequence, not the textbook definition. Every `keyPoint` is the detail that
// separates a strong answer from a memorised one, and never a restatement of the answer.

export const csTopics: CsTopic[] = [
  {
    id: 'cst-os',
    area: 'os',
    name: 'Operating Systems',
    order: 1,
    summary: 'Processes and threads, context switching, virtual memory and paging, page faults and thrashing, the TLB, fork and copy-on-write, process lifecycle, IPC, and CPU scheduling. The largest single slice of the Amazon CS-fundamentals round and the core of the Meta Production Engineer screen.',
  },
  {
    id: 'cst-networking',
    area: 'networking',
    name: 'Networking',
    order: 2,
    summary: 'TCP versus UDP, the handshake and teardown, congestion control, head-of-line blocking across HTTP/1.1, HTTP/2 and HTTP/3, DNS resolution, TLS and what a certificate proves, L4 versus L7 load balancing, CDNs, NAT, proxies, CIDR, and how to bisect a connectivity problem layer by layer.',
  },
  {
    id: 'cst-databases',
    area: 'databases',
    name: 'Databases',
    order: 3,
    summary: 'ACID with the mechanism underneath it, the four isolation levels and the anomaly each one permits, normalisation and when to trade it away, B-tree versus hash indexes, composite and clustered index design, reading a query plan, database deadlocks, MVCC, and optimistic versus pessimistic locking.',
  },
  {
    id: 'cst-concurrency',
    area: 'concurrency',
    name: 'Concurrency',
    order: 4,
    summary: 'Race conditions, mutexes, semaphores and spinlocks, monitors, the producer-consumer problem, the four necessary conditions for deadlock plus detection and prevention, livelock and starvation, atomics and compare-and-swap, and the hardware layer underneath: cache coherence and false sharing.',
  },
  {
    id: 'cst-oop',
    area: 'oop',
    name: 'OOP Fundamentals',
    order: 5,
    summary: 'The object-oriented questions interviewers ask as a knowledge check, separately from a low-level design exercise: what encapsulation actually buys, overloading versus overriding, how dynamic dispatch works, composition versus inheritance and why to favour composition, Liskov substitution, equality and hashing, immutability, and dependency inversion.',
  },
]

// ------------------------------------------------------------------ Operating systems
const osQuestions: CsQuestion[] = [
  {
    id: 'csq-process-vs-thread',
    topicId: 'cst-os',
    text: 'What is the difference between a process and a thread?',
    answer: "A process is an independent unit with its own virtual address space, its own page table, its own file descriptor table and its own heap - the kernel isolates it from every other process. A thread is a schedulable unit inside a process: it gets its own stack, registers and program counter, but shares the address space, the heap, the descriptors and the loaded code with its siblings. So sharing data between threads is just a pointer; sharing between processes needs a pipe, a socket, or an explicit shared-memory mapping.",
    keyPoint: 'Isolation is the thing you are paying for, not an accident of the design. One misbehaving thread can corrupt shared heap state and take the whole process down, while a crashing process leaves its siblings untouched - which is exactly why a browser puts tabs in separate processes rather than threads.',
    companies: ['amazon', 'meta'],
    minutes: 7,
  },
  {
    id: 'csq-context-switch-cost',
    topicId: 'cst-os',
    text: 'Why is a process context switch more expensive than a thread context switch?',
    answer: "A thread switch saves and restores the register set and swaps the stack pointer; the address space does not change, so the page table stays installed and the caches stay warm. A process switch additionally loads a new page-table base register, which invalidates the translations cached for the old address space, so the first stretch of memory accesses after the switch each pay a full page-table walk. Saving registers is nanoseconds - the cold TLB and cold L1 are what actually cost you.",
    keyPoint: 'Naming the indirect cost is what makes the answer land, and then hedging it correctly: modern CPUs tag translations with an address-space identifier (PCID on x86, ASID on ARM) specifically to avoid flushing the whole thing, so the accurate version is a flush unless the hardware supports tagged entries.',
    companies: ['amazon', 'meta'],
    minutes: 7,
  },
  {
    id: 'csq-virtual-memory',
    topicId: 'cst-os',
    text: 'What is virtual memory and why does it exist?',
    answer: "Virtual memory gives every process its own flat address space that the MMU translates into physical frames through a page table. It buys two things. Isolation, because a process cannot even name another process's memory - there is no address it can form that reaches it. And the illusion of more memory than you physically have, because cold pages can live on disk and be faulted back in on demand. It also makes relocation free: the loader does not care which physical frames the pages land in.",
    keyPoint: 'The third win is the one candidates skip: translation makes controlled sharing cheap. Two processes can map the same physical frame, so a shared library is paid for once across hundreds of processes, and a shared-memory IPC segment is just one frame appearing in two page tables.',
    companies: ['amazon', 'meta'],
    minutes: 7,
  },
  {
    id: 'csq-paging-vs-segmentation',
    topicId: 'cst-os',
    text: 'Paging versus segmentation - what is the difference, and which do real systems use?',
    answer: "Paging cuts the address space into fixed-size pages, typically 4 KB, and physical memory into frames of the same size, so any page fits any frame. Segmentation cuts it into variable-length, logically meaningful pieces - code, data, stack - which matches how a programmer thinks about a program and makes per-region protection natural. Real systems manage memory with paging and keep segmentation only vestigially, mostly as a protection and addressing artefact.",
    keyPoint: 'The decision is which kind of fragmentation you are willing to accept. Fixed-size units waste part of the final unit per region, a bounded cost, while variable-length units leave unusable gaps between allocations that grow without bound and can only be reclaimed by compaction. Bounded waste beats unbounded waste.',
    companies: ['amazon'],
    minutes: 6,
  },
  {
    id: 'csq-page-fault',
    topicId: 'cst-os',
    text: 'What is a page fault, and what is the difference between a major and a minor fault?',
    answer: "A page fault is the MMU trapping into the kernel because the virtual page you touched has no valid mapping to a physical frame. A minor fault means the data is already in memory somewhere - it is in the page cache, or it is a copy-on-write page, or the mapping simply had not been installed yet - so the kernel fixes up the page table and returns in microseconds. A major fault means the kernel has to fetch from disk, which is milliseconds: four to five orders of magnitude worse.",
    keyPoint: 'The operational reading beats the definition here. High minor-fault counts are normal and largely harmless - every freshly mapped page produces one - whereas a climbing major rate is the signal that your working set no longer fits in RAM and the machine is on its way to thrashing.',
    companies: ['meta'],
    minutes: 6,
  },
  {
    id: 'csq-thrashing',
    topicId: 'cst-os',
    text: 'What is thrashing, how do you detect it, and how do you fix it?',
    answer: "Thrashing is when the combined working set of the runnable processes exceeds physical memory, so each process's next instruction evicts a page that another process immediately needs back. You detect it from the shape of the symptoms: CPU utilisation collapses while disk utilisation pins near 100%, so the machine looks idle and is completely unresponsive. The fix is to reduce the degree of multiprogramming - suspend or kill processes until the resident sets fit - or add memory.",
    keyPoint: 'The interesting part is the feedback loop that makes it self-reinforcing: a naive scheduler sees low CPU utilisation, concludes the machine is underloaded and admits more work, which deepens the shortage. That is precisely why working-set and page-fault-frequency based admission control exists.',
    companies: ['amazon', 'meta'],
    minutes: 7,
  },
  {
    id: 'csq-tlb',
    topicId: 'cst-os',
    text: 'What is the TLB and why does it matter for performance?',
    answer: "The TLB is a small, very fast cache of virtual-to-physical page translations sitting in front of the page tables. Without it every memory access would need a page-table walk, and on x86-64 a four-level table means several extra memory accesses for every single access your program makes. Hit rates in practice are very high, which is why the walk cost is invisible - right up until you run a workload whose access pattern defeats it.",
    keyPoint: 'Coverage is the concept that makes this concrete: the TLB holds only a few hundred to a couple of thousand entries, so at 4 KB apiece it maps only a few megabytes at a time. A large random-access working set therefore misses constantly, and that is exactly the problem huge pages solve - each entry then covers 2 MB or 1 GB.',
    companies: ['meta'],
    minutes: 7,
  },
  {
    id: 'csq-fork-cow',
    topicId: 'cst-os',
    text: 'What happens in memory when you call fork()?',
    answer: "fork() gives the child a copy of the parent's address space, but the kernel copies no data pages at all. It copies the page table and marks every writable page read-only in both processes. The first write from either side traps into the kernel, which allocates a fresh frame, copies that one page and clears the read-only bit for the writer. So the cost of fork is proportional to the size of the page table, not the size of the address space, and pages that are only ever read stay shared indefinitely.",
    keyPoint: 'The consequence is that the memory cost is deferred rather than avoided, and that surprises people in production: a large parent that forks and then has both sides touch most of their pages suddenly needs close to double the RAM. That is the mechanism behind the memory spike when an in-memory datastore forks to write a snapshot.',
    companies: ['meta'],
    minutes: 8,
  },
  {
    id: 'csq-fork-vs-exec',
    topicId: 'cst-os',
    text: 'What is the difference between fork() and exec()?',
    answer: "fork() duplicates the calling process and returns twice - zero in the child, the child's pid in the parent. exec() creates nothing: it replaces the current process's address space with a new program image, keeping the same pid and, by default, the same open file descriptors. Every command your shell runs is the pair: fork, then exec in the child, while the parent waits for it.",
    keyPoint: 'The reason the two are split rather than fused into one spawn call is the window between them. That is where the child rearranges its own environment before the new program starts - dup2 a pipe onto stdout, close descriptors it should not inherit, chdir, drop privileges - which is exactly how shell redirection and pipelines are implemented.',
    companies: ['meta'],
    minutes: 6,
  },
  {
    id: 'csq-zombie-vs-orphan',
    topicId: 'cst-os',
    text: 'What is a zombie process, and how is it different from an orphan?',
    answer: "A zombie has already exited, but its parent has not called wait() yet, so the kernel keeps its exit status and its entry in the process table. It holds no memory and no descriptors - just the table slot and the pid. An orphan is the inverse: the parent died first, so init or the nearest subreaper adopts the child and will reap it when it exits. Zombies are a bug in the parent; orphans are handled by the system for you.",
    keyPoint: 'They only matter in bulk, and that is the follow-up: each one pins a pid, so a long-lived parent that forks in a loop and never reaps will exhaust the pid table until nobody on the box can start anything. The fix is waitpid() from a SIGCHLD handler, or explicitly setting SIGCHLD to SIG_IGN so the kernel reaps for you.',
    companies: ['meta'],
    minutes: 6,
  },
  {
    id: 'csq-hard-vs-symlink',
    topicId: 'cst-os',
    text: 'Hard link versus symbolic link?',
    answer: "A hard link is a second directory entry pointing at the same inode, so the two names are genuinely indistinguishable - there is no original - and the data is freed only when the link count reaches zero and no process still holds the file open. A symlink is its own inode whose content is a path string, resolved afresh at every lookup, so it can cross filesystems and point at a directory, and it dangles harmlessly if the target disappears.",
    keyPoint: 'Late resolution is what makes symlinks operationally useful: because the path is followed on every open, you can atomically repoint a live path by rename()-ing a new link over the old one. That is how a deployment scheme swaps a stable path onto a new release directory with no window where it points at nothing.',
    companies: ['meta'],
    minutes: 6,
  },
  {
    id: 'csq-ipc-mechanisms',
    topicId: 'cst-os',
    text: 'What IPC mechanisms are there, and how do you choose between them?',
    answer: "Pipes and sockets are byte streams the kernel copies through: simple and safe, and you pay a copy in each direction plus a syscall per message. Pipes for a parent and child on one box, Unix domain sockets for unrelated local processes, TCP sockets once you cross machines. Message queues give you discrete, optionally prioritised messages with kernel-managed buffering and no framing work. Shared memory is the fast one - after the mapping is set up, transfers happen at memory speed with no kernel involvement - but the kernel gives you no synchronisation, so you bring your own semaphore or futex.",
    keyPoint: 'Choose on the copy-versus-coordination tradeoff rather than on familiarity. Shared memory is the only mechanism that avoids kernel copies, and it is therefore the only one where the concurrency control is your problem and a data race is possible; everything else serialises through the kernel and is race-free by construction.',
    companies: ['amazon', 'meta'],
    minutes: 8,
  },
  {
    id: 'csq-cpu-scheduling',
    topicId: 'cst-os',
    text: 'Walk me through the CPU scheduling algorithms and their tradeoffs.',
    answer: "FCFS is trivial and fair in arrival order, but one long job at the head wrecks average waiting time for everything behind it - the convoy effect. Shortest-job-first is provably optimal for average waiting time, but it needs burst lengths you do not have and it starves long jobs. Round robin bounds the time before any job gets the CPU, which is what interactive work needs, and pays for it in extra context switches. Multi-level feedback queues are what real kernels approximate: start every job at high priority and demote it as it consumes full quanta, so the scheduler infers which jobs are interactive instead of being told.",
    keyPoint: 'The interesting part of MLFQ is the safeguards, not the demotion. Without periodic priority boosting a long CPU-bound job that turns interactive stays stuck at the bottom forever, and without accounting for total quantum consumed rather than per-slice yielding, a process games its way into permanent high priority by relinquishing the CPU just before each slice expires.',
    companies: ['amazon'],
    minutes: 9,
  },
  {
    id: 'csq-priority-inversion',
    topicId: 'cst-os',
    text: 'What is priority inversion and how is it solved?',
    answer: "Priority inversion is when a high-priority task blocks on a lock held by a low-priority task, and then a medium-priority task that wants neither preempts the lock holder. The highest-priority task now waits, indirectly, on the lowest, for an unbounded time. Priority inheritance fixes it by temporarily raising the holder to the priority of the highest waiter so nothing in between can preempt it. Priority ceiling is the stricter variant: the holder immediately runs at the ceiling priority of any task that could ever acquire that lock.",
    keyPoint: 'What makes this worth understanding rather than memorising is that the locking code is correct - the scheduling policy is what is wrong - so the failure survives code review and unit testing and only appears under a particular timing. The Mars Pathfinder watchdog resets in 1997 are the canonical case, and were fixed by turning inheritance on.',
    companies: [],
    minutes: 7,
  },
  {
    id: 'csq-threading-models',
    topicId: 'cst-os',
    text: 'Explain the 1:1, N:1 and M:N multithreading models.',
    answer: "1:1 maps each user thread onto its own kernel thread: real parallelism across cores, and the kernel sees a blocking call so only that thread stops - but each thread costs a kernel stack and creating one is a syscall. This is what Linux and Windows do. N:1 multiplexes many user threads onto a single kernel thread: creation is almost free, but one blocking syscall stalls every thread and you can never use more than one core. M:N maps M user threads onto N kernel threads, which gets you cheap threads and parallelism at the cost of a substantially harder two-level scheduler.",
    keyPoint: 'M:N is where modern language runtimes live - goroutines and Java virtual threads are userspace schedulers riding on 1:1 kernel threads - and the hard part is the N:1 problem in miniature: the runtime has to notice a blocking syscall and hand the carrier thread off, or a single blocking call stalls everything queued behind it.',
    companies: [],
    minutes: 7,
  },
]

// ------------------------------------------------------------------------ Networking
const networkingQuestions: CsQuestion[] = [
  {
    id: 'csq-tcp-vs-udp',
    topicId: 'cst-networking',
    text: 'TCP versus UDP - what is the difference and when would you use each?',
    answer: "TCP is connection-oriented: a handshake establishes state on both ends, and the protocol then gives you reliable, in-order, byte-stream delivery with retransmission, flow control and congestion control, at a minimum of 20 bytes of header. UDP is a thin wrapper over IP - 8 bytes of header, no handshake, no retransmission, no ordering, no congestion control. You reach for UDP when a late packet is worthless rather than useful: voice and video, gaming, and single-datagram request/response like DNS.",
    keyPoint: 'The framing that separates a strong answer is that UDP is not a worse TCP, it is the substrate you build your own transport on. QUIC runs over UDP and reimplements reliability, ordering and congestion control in userspace precisely so it can evolve without waiting for kernel upgrades and middlebox tolerance.',
    companies: ['amazon', 'meta'],
    minutes: 7,
  },
  {
    id: 'csq-tcp-handshake',
    topicId: 'cst-networking',
    text: 'Walk me through the TCP three-way handshake, and why teardown takes four messages.',
    answer: "The client sends SYN carrying its initial sequence number; the server replies SYN-ACK, acknowledging that number and offering its own; the client ACKs. It takes three messages because both directions need a sequence number established and acknowledged, and the server's SYN and its ACK ride together. Teardown takes four because closing is independent per direction: each side sends FIN and receives an ACK, so one side can stop sending while the other keeps streaming - a half-close.",
    keyPoint: 'The follow-up is almost always TIME_WAIT: whichever side closes first waits roughly twice the maximum segment lifetime so a delayed duplicate cannot be delivered into a fresh connection reusing the same four-tuple. That wait is why a busy client-side box exhausts its ephemeral port range and starts refusing outbound connections.',
    companies: ['amazon', 'meta'],
    minutes: 8,
  },
  {
    id: 'csq-tcp-congestion-control',
    topicId: 'cst-networking',
    text: 'How does TCP congestion control work?',
    answer: "The sender maintains a congestion window and grows it carefully. Slow start doubles the window every round trip until it reaches a threshold or hits a loss, so you probe the path's capacity exponentially instead of blasting it. Past the threshold, congestion avoidance grows the window by about one segment per round trip - additive increase. On three duplicate ACKs, fast retransmit resends the missing segment and fast recovery halves the window rather than collapsing; on a timeout, which signals something worse than one dropped packet, the sender does fall back to slow start.",
    keyPoint: 'Say out loud what the signal actually is: classic TCP infers congestion from loss, so it misreads a lossy wireless link as a congested one and badly under-uses it. That limitation is the whole reason for loss-agnostic algorithms like BBR, which model bottleneck bandwidth and round-trip time instead of waiting for a drop.',
    companies: ['amazon'],
    minutes: 9,
  },
  {
    id: 'csq-head-of-line-blocking',
    topicId: 'cst-networking',
    text: 'What is head-of-line blocking, and does HTTP/2 solve it?',
    answer: "Head-of-line blocking is one stalled item at the front of a queue holding up everything behind it that could otherwise have been served. HTTP/1.1 has it at the application layer - one outstanding request per connection - which is why browsers opened six connections per host. HTTP/2 fixes the application layer with multiplexed streams over a single connection, but it still runs on TCP, and TCP delivers one ordered byte stream, so a single lost segment stalls every stream sharing that connection. HTTP/3 moves to QUIC, where each stream has its own delivery order, so a loss stalls only its own stream.",
    keyPoint: 'The nuance worth volunteering is that HTTP/2 made the transport-layer case worse rather than better under loss: collapsing six connections into one means a single dropped segment now blocks all of your in-flight requests instead of roughly a sixth of them.',
    companies: ['amazon'],
    minutes: 8,
  },
  {
    id: 'csq-http-versions',
    topicId: 'cst-networking',
    text: 'HTTP/1.1 versus HTTP/2 versus HTTP/3 - what changed and why?',
    answer: "HTTP/1.1 is text on the wire with one outstanding request per connection, so parallelism came from opening several connections. HTTP/2 keeps the same semantics but changes the framing to binary, multiplexes many streams over one TCP connection, and compresses headers with HPACK so repeated cookie and user-agent lines stop dominating small requests. HTTP/3 keeps HTTP/2's semantics and replaces the transport: QUIC over UDP, with per-stream ordering, the TLS handshake folded into the transport handshake, and connection IDs so a session survives the client changing network.",
    keyPoint: 'What changed across all three is the transport and the encoding, never the semantics - methods, status codes and header meanings are constant - so the clean summary is that HTTP/2 fixed application-layer multiplexing and HTTP/3 fixed the transport-layer consequence of having done so.',
    companies: ['amazon'],
    minutes: 8,
  },
  {
    id: 'csq-quic-over-udp',
    topicId: 'cst-networking',
    text: 'Why is QUIC built on UDP rather than on TCP?',
    answer: "QUIC needs to own ordering, loss recovery and the handshake itself, and TCP is implemented in the kernel and ossified by middleboxes that inspect and rewrite its headers - you cannot ship a new TCP and expect it to traverse the internet. UDP is the one transport that is universally forwarded and does essentially nothing, so QUIC uses it as a bare datagram substrate and rebuilds reliability, congestion control and per-stream ordering above it. That also lets it merge the transport and TLS handshakes into a single round trip, or zero on resumption.",
    keyPoint: 'Explain why it is deployable rather than just why it is nicer: putting the transport in userspace means a browser and a server can both upgrade congestion control in a normal software release, whereas changing TCP waits on kernel upgrades across every operating system and every middlebox in the path.',
    companies: ['amazon'],
    minutes: 7,
  },
  {
    id: 'csq-dns-resolution',
    topicId: 'cst-networking',
    text: 'Walk me through the full DNS resolution path for a name you have never looked up.',
    answer: "The browser checks its own cache first, then hands the name to the OS resolver, which checks its cache and the hosts file. On a miss it goes to the configured recursive resolver, and that resolver does the walk: ask a root server, which does not know the answer but refers you to the servers for the top-level domain; ask one of those, which refers you to the authoritative name servers for the domain; ask one of those, which returns the actual A or AAAA record. The resolver caches the result for its TTL and hands it back, so the full walk happens rarely.",
    keyPoint: 'The distinction to draw is that the query is recursive only from the client to its resolver, and iterative from there: the root and TLD servers never chase referrals on your behalf, they only ever answer with a pointer to someone closer. That is exactly what lets a dozen root server addresses serve the whole internet.',
    companies: ['amazon', 'meta'],
    minutes: 8,
  },
  {
    id: 'csq-dns-udp-tcp',
    topicId: 'cst-networking',
    text: 'Why does DNS use UDP, and when does it fall back to TCP?',
    answer: "DNS uses UDP because a query and its answer usually fit in a single small datagram, and one connectionless round trip is far cheaper than a handshake for something clients do constantly. If a response is larger than what the requester said it could accept, the server sets the truncated bit and the client retries the identical query over TCP. Zone transfers between name servers use TCP unconditionally, because those are bulk and must arrive reliably and in order.",
    keyPoint: 'The size limit is negotiated rather than fixed at the old 512-byte ceiling: EDNS0 lets a client advertise a bigger acceptable payload, which is what makes DNSSEC-sized responses viable without falling back. It is also what made DNS a favourite amplification vector, since a small spoofed query can elicit a very large reply.',
    companies: ['amazon', 'meta'],
    minutes: 7,
  },
  {
    id: 'csq-type-a-url',
    topicId: 'cst-networking',
    text: 'What happens when you type a URL into a browser and press enter?',
    answer: "The browser first has to decide what you even typed - a search term or a host - then normalises it and checks its HSTS list, so a site on that list gets upgraded to https before a single byte leaves the machine. It needs an address, so it walks its own cache, the OS resolver, and if necessary the recursive resolver's descent from the root. With an address it opens a TCP connection to port 443, and the TLS handshake rides straight on top: the server presents a certificate chain, the browser validates it up to a root it already trusts and checks the name matches what it asked for, both sides derive session keys, and from there the bytes are encrypted. The browser sends a GET with the Host header and any cookies for that origin, and what usually answers is not the origin at all but a CDN edge terminating TLS near you, serving from cache or fetching through a load balancer to an application server. The response comes back and the browser parses HTML into a DOM, discovers subresources and starts fetching them, builds the CSSOM, blocks on synchronous scripts, then lays out and paints - and the first paint normally happens long before the last subresource has landed.",
    keyPoint: 'What separates a strong answer is naming where the latency actually lives and that most of these steps usually do not happen at all. Name resolution, connection setup and the cryptographic handshake are round trips you only pay on a cold path, and HSTS preloading, connection reuse, session resumption and anycast edges exist specifically to delete them - on a warm visit the request goes straight out over a connection that is already open.',
    companies: ['amazon', 'meta'],
    minutes: 10,
  },
  {
    id: 'csq-tls-handshake',
    topicId: 'cst-networking',
    text: 'Walk me through the TLS handshake. What does a certificate actually prove?',
    answer: "The client sends a hello listing the versions and cipher suites it supports along with a key share; the server picks a suite, returns its certificate chain and its own key share, and both sides derive identical session keys from the exchange without ever sending them. The browser then validates the chain: each certificate is signed by the next one up, terminating at a root already in its trust store, and it checks that the name in the certificate covers the host it asked for and that the certificate is neither expired nor revoked. After that the connection switches to symmetric encryption, because public-key operations are far too slow for bulk data.",
    keyPoint: 'Be precise about the scope of the guarantee: a certificate proves only that some authority the client trusts vouched that this public key belongs to this domain name. It says nothing about the operator being honest or the content being safe, which is why a phishing site can and routinely does hold a perfectly valid certificate.',
    companies: ['amazon'],
    minutes: 9,
  },
  {
    id: 'csq-l4-vs-l7',
    topicId: 'cst-networking',
    text: 'Layer 4 versus Layer 7 load balancing - what is the difference?',
    answer: "An L4 balancer decides on the IP and port four-tuple without looking inside the payload, so it forwards at very high throughput and, with TLS, does not need the keys at all - it just passes the encrypted bytes along. An L7 balancer terminates the connection, parses the HTTP request, and can therefore route on path, header, cookie or method, retry a failed request against a different backend, and rewrite or compress on the way through. The price is that it has to decrypt, which means holding certificates and spending real CPU per request.",
    keyPoint: 'The decision reduces to where you want to terminate TLS and whether you need per-request behaviour, because at L4 you cannot tell one request from the next inside a connection. Retries, canary routing by header, and per-endpoint rate limiting are simply not expressible below the application layer.',
    companies: ['amazon'],
    minutes: 7,
  },
  {
    id: 'csq-lb-algorithms',
    topicId: 'cst-networking',
    text: 'Round robin, least connections, consistent hashing - when is each right?',
    answer: "Round robin is right when backends are identical and requests are short and uniform: it needs no state and it is fair by count. Least connections is right when request durations vary a lot, because in-flight work is a far better proxy for load than arrival count - a backend stuck on slow requests stops receiving new ones automatically. Consistent hashing is for when a request has to reach a particular node, like a cache shard or a sticky session: keys map onto a ring so adding or removing one node out of n relocates only about one nth of the keys instead of remapping everything.",
    keyPoint: 'Consistent hashing on its own distributes badly with a small number of nodes, which is why every real implementation assigns each physical node many virtual positions on the ring, and why bounded-load variants exist to stop one hot key pinning a single shard while its neighbours idle.',
    companies: ['amazon'],
    minutes: 8,
  },
  {
    id: 'csq-cdn',
    topicId: 'cst-networking',
    text: 'How does a CDN reduce latency?',
    answer: "A CDN places copies of your content in points of presence around the world and uses anycast routing so each user's packets land at the nearest one, which cuts the round-trip time from cross-continent to tens of milliseconds. That matters more than it first sounds, because every round trip on the critical path is multiplied by it: connection setup, the cryptographic handshake and any redirect all pay the same figure. Edges also terminate TLS locally and hold warm connections back to origin, so even a cache miss beats going the whole way yourself.",
    keyPoint: 'Latency is not the only reason to want one. The edge absorbs the bulk of read traffic and volumetric attacks, so origin capacity gets sized for cache misses and writes rather than for peak load - usually a larger operational win than the milliseconds it saves.',
    companies: ['amazon'],
    minutes: 7,
  },
  {
    id: 'csq-nat',
    topicId: 'cst-networking',
    text: 'What is NAT and why does it exist?',
    answer: "NAT exists because IPv4 has roughly four billion addresses and there are far more devices than that, so a network shares one public address across many hosts by rewriting the source address and port on outbound packets and keeping a translation table to reverse it on the way back. That table is the whole trick, and it is populated by outbound traffic - which is why an unsolicited inbound packet has no entry to match and nowhere to be delivered.",
    keyPoint: 'The side effect became a feature and then a problem. You get accidental inbound firewalling for free, but you also break any protocol that carries addresses inside its payload or wants direct peer-to-peer connectivity, which is the entire reason STUN, TURN and hole punching had to be invented.',
    companies: ['meta'],
    minutes: 6,
  },
  {
    id: 'csq-forward-vs-reverse-proxy',
    topicId: 'cst-networking',
    text: 'Forward proxy versus reverse proxy?',
    answer: "A forward proxy sits in front of clients and acts on their behalf: the client is configured to use it, and the origin server sees the proxy's address rather than the client's. That is a corporate egress filter or a caching gateway. A reverse proxy sits in front of servers and acts on their behalf: the client believes it is talking to the origin, and the proxy fans requests out to a pool behind it. That is nginx, an L7 load balancer, or a CDN edge. Same mechanism, opposite side of the conversation.",
    keyPoint: 'Ask which side is hidden and which side needs configuring, because that framing survives every variant of the question: a forward proxy conceals clients from the server and requires client-side setup, while a reverse proxy conceals servers from the client and requires nothing of the client at all.',
    companies: ['amazon'],
    minutes: 6,
  },
  {
    id: 'csq-https-guarantees',
    topicId: 'cst-networking',
    text: 'How does HTTPS give you confidentiality, integrity and authentication?',
    answer: "Confidentiality comes from symmetric encryption of the session using keys derived during the handshake, so an observer on the path sees only ciphertext. Integrity comes from the authentication tag an AEAD cipher attaches to every record, so a tampered, truncated or reordered record is rejected rather than silently accepted. Authentication comes from the certificate chain: the server proves it holds the private key matching a public key that a trusted authority bound to this domain name.",
    keyPoint: 'Name what it deliberately does not hide, because that is where the follow-up goes: the destination address, the packet sizes and timing, and - until encrypted client hello is widely deployed - the hostname in the SNI field. An observer usually still learns which site you visited even though the content is opaque.',
    companies: ['amazon'],
    minutes: 7,
  },
  {
    id: 'csq-cidr',
    topicId: 'cst-networking',
    text: 'Explain subnet masks and CIDR. How many usable hosts are in a /26?',
    answer: "The mask splits an address into a network part and a host part, and the CIDR prefix is just how many leading bits are the network: a /24 means 24 network bits and 8 host bits. Usable hosts is two to the power of the remaining bits, minus two, because the all-zeros host is the network address and the all-ones host is the broadcast address. So a /24 gives 254 usable and a /26 gives 62. Each extra prefix bit halves the block, which is exactly what subnetting does.",
    keyPoint: 'Point-to-point links are the exception that shows you understand the arithmetic rather than the formula: a /31 has no room for a network and a broadcast address and is nevertheless valid for a two-host link under RFC 3021, and a /32 is a single host route with no host space at all.',
    companies: ['meta'],
    minutes: 6,
  },
  {
    id: 'csq-osi-model',
    topicId: 'cst-networking',
    text: 'Explain the OSI model and how it maps onto TCP/IP.',
    answer: "Seven layers, but in practice you map them onto the four-layer TCP/IP stack. Physical and data link are the cable and the Ethernet frame with MAC addresses, switched within one network. Network is IP, which routes between networks and gives you addressing that survives hops. Transport is TCP and UDP, which give you ports and, for TCP, reliability and flow control. Session, presentation and application collapse into a single application layer where HTTP, TLS and DNS all live.",
    keyPoint: 'The value of the model is that it tells you which layer a symptom belongs to, and the honest caveat is that TLS fits none of the seven cleanly - it sits between transport and application - which is exactly why practitioners work in the four-layer stack and treat the seven names as shared vocabulary.',
    companies: ['amazon'],
    minutes: 6,
  },
  {
    id: 'csq-network-troubleshooting',
    topicId: 'cst-networking',
    text: 'A service is unreachable from one host. How do you debug it?',
    answer: "I work up the stack so each command eliminates a layer. Is it name resolution - dig the record and compare it against what the application actually resolved. Is the host reachable - ping for basic reachability, then traceroute or mtr to see where the path stops. Is the port open - a plain TCP connect with nc separates a host that is up with a dead service from a network that is dropping the packets. Is it the application - curl with timing breaks the request into connect time, handshake time and server time. Then I look at the box itself: ss for socket states, vmstat and iostat for saturation, iftop for who is using the link.",
    keyPoint: 'The discipline is bisecting rather than guessing, and two socket states carry most of the diagnosis on their own: a pile of SYN_SENT means your packets are not arriving or not being answered, while a pile of CLOSE_WAIT means the remote side closed and your own application is failing to close its sockets.',
    companies: ['meta'],
    minutes: 9,
  },
]

export const csQuestions: CsQuestion[] = [...osQuestions, ...networkingQuestions]
