import type { DsaPattern, DsaProblem } from '@/lib/content/schema'

export const dsaPatterns: DsaPattern[] = [
  {
    id: 'dsap-arrays-hashing',
    name: 'Arrays & Hashing',
    order: 1,
    signals: [
      'You need to count, group, or deduplicate values in one pass.',
      'The brute force is a nested loop over pairs and you want O(n).',
      'The question asks whether something has been seen before.',
    ],
    template: `# Count or index by value in one pass.
seen = {}
for i, x in enumerate(nums):
    if target - x in seen:
        return [seen[target - x], i]
    seen[x] = i
return []`,
    pitfalls: [
      'Writing the current value into the map before checking for its complement, which lets an element pair with itself.',
      'Using a list instead of a set for membership tests, turning O(n) into O(n^2).',
      'Forgetting that dict ordering is insertion order, not sorted order.',
    ],
  },
  {
    id: 'dsap-two-pointers',
    name: 'Two Pointers',
    order: 2,
    signals: [
      'The input is sorted, or sorting it does not lose information you need.',
      'You are looking for a pair or triple that satisfies a condition.',
      'You need to compare the ends of an array or string moving inward.',
    ],
    template: `# Converge from both ends on a sorted array.
lo, hi = 0, len(nums) - 1
while lo < hi:
    total = nums[lo] + nums[hi]
    if total == target:
        return [lo, hi]
    if total < target:
        lo += 1
    else:
        hi -= 1
return []`,
    pitfalls: [
      'Forgetting to skip duplicates after a match, which produces repeated answers in 3Sum.',
      'Using <= instead of < in the loop guard, which lets both pointers land on the same index.',
    ],
  },
  {
    id: 'dsap-sliding-window',
    name: 'Sliding Window',
    order: 3,
    signals: [
      'You need the best contiguous subarray or substring under a constraint.',
      'The brute force recomputes a window sum or count from scratch each time.',
      'The constraint is monotonic: growing the window only ever helps or only ever hurts.',
    ],
    template: `# Expand right, shrink left while the window is invalid.
left = 0
best = 0
count: dict[str, int] = {}
for right, ch in enumerate(s):
    count[ch] = count.get(ch, 0) + 1
    while invalid(count):
        count[s[left]] -= 1
        left += 1
    best = max(best, right - left + 1)
return best`,
    pitfalls: [
      'Shrinking the window with an if instead of a while, so it stops one step early when multiple shrinks are needed.',
      'Recomputing the window state from scratch on every right-pointer step instead of updating incrementally.',
    ],
  },
  {
    id: 'dsap-stack',
    name: 'Stack',
    order: 4,
    signals: [
      'You need to match nested pairs, like parentheses or tags.',
      'You are looking for the next greater or smaller element relative to each position.',
      'Undoing the most recent unresolved operation solves the problem (monotonic stack or expression eval).',
    ],
    template: `# Monotonic decreasing stack of indices for next-greater-element.
stack: list[int] = []
result = [0] * len(nums)
for i, x in enumerate(nums):
    while stack and nums[stack[-1]] < x:
        j = stack.pop()
        result[j] = i - j
    stack.append(i)
return result`,
    pitfalls: [
      'Popping the stack without checking it is non-empty first, causing an index error.',
      'Pushing values instead of indices when the answer depends on distance or position.',
    ],
  },
  {
    id: 'dsap-binary-search',
    name: 'Binary Search',
    order: 5,
    signals: [
      'The search space is sorted, or is monotonic even if the array itself is not (search on the answer).',
      'You need the boundary where a predicate flips from false to true.',
      'A linear scan works but the input size demands O(log n).',
    ],
    template: `# Search on the answer: find smallest x where feasible(x) is true.
lo, hi = low_bound, high_bound
while lo < hi:
    mid = (lo + hi) // 2
    if feasible(mid):
        hi = mid
    else:
        lo = mid + 1
return lo`,
    pitfalls: [
      'Using mid = (lo + hi) // 2 with hi = mid instead of mid - 1 inconsistently, causing an infinite loop.',
      'Forgetting to handle the rotated-array case where one half is sorted and the other is not.',
    ],
  },
  {
    id: 'dsap-linked-list',
    name: 'Linked List',
    order: 6,
    signals: [
      'You need to reverse, reorder, or detect a cycle without extra memory.',
      'The problem gives you a singly linked list and forbids converting it to an array.',
      'You need a fast and slow pointer to find a midpoint, cycle, or nth-from-end node.',
    ],
    template: `# Reverse a singly linked list iteratively.
prev = None
curr = head
while curr:
    nxt = curr.next
    curr.next = prev
    prev = curr
    curr = nxt
return prev`,
    pitfalls: [
      'Losing the reference to the next node before reassigning curr.next, orphaning the rest of the list.',
      'Forgetting a dummy head node, which complicates edge cases where the head itself is removed or replaced.',
    ],
  },
  {
    id: 'dsap-trees',
    name: 'Trees',
    order: 7,
    signals: [
      'The input is a binary tree or BST and you need depth, path, or structural comparison.',
      'A property must hold recursively for every subtree (balanced, same, valid BST).',
      'You need a level-by-level view, which points to BFS over DFS.',
    ],
    template: `# DFS returning a pair of (subtree valid, aggregated value).
def dfs(node, lo=float('-inf'), hi=float('inf')):
    if not node:
        return True
    if not (lo < node.val < hi):
        return False
    return dfs(node.left, lo, node.val) and dfs(node.right, node.val, hi)
return dfs(root)`,
    pitfalls: [
      'Validating a BST by only comparing a node to its immediate children instead of threading min/max bounds down the recursion.',
      'Using recursion depth equal to tree height without considering a skewed tree can blow the call stack.',
    ],
  },
  {
    id: 'dsap-heap',
    name: 'Heap / Priority Queue',
    order: 8,
    signals: [
      'You repeatedly need the current min or max as the data set changes.',
      'The question says "kth largest/smallest" or "top k".',
      'You need to merge many sorted sources or schedule by priority.',
    ],
    template: `# Maintain the k largest seen so far with a min-heap of size k.
import heapq
heap: list[int] = []
for x in nums:
    heapq.heappush(heap, x)
    if len(heap) > k:
        heapq.heappop(heap)
return heap[0]`,
    pitfalls: [
      'Using a max-heap approach that keeps every element instead of a bounded min-heap of size k, costing extra memory and time.',
      "Forgetting Python's heapq is min-heap only, so max-heap behavior needs negated values.",
    ],
  },
  {
    id: 'dsap-backtracking',
    name: 'Backtracking',
    order: 9,
    signals: [
      'You need all combinations, subsets, or permutations satisfying a constraint.',
      'A greedy or DP shortcut does not exist because you must enumerate, not just count.',
      'The problem allows pruning: an invalid partial choice can be abandoned early.',
    ],
    template: `# Build subsets by choosing to include or skip each index.
def backtrack(i, path):
    if i == len(nums):
        result.append(path[:])
        return
    path.append(nums[i])
    backtrack(i + 1, path)
    path.pop()
    backtrack(i + 1, path)
backtrack(0, [])`,
    pitfalls: [
      'Appending a reference to the mutable path list instead of a copy, so later mutations corrupt saved results.',
      'Forgetting to undo (pop) a choice before trying the next branch, leaking state across siblings.',
    ],
  },
  {
    id: 'dsap-tries',
    name: 'Tries',
    order: 10,
    signals: [
      'You need fast prefix lookups across many strings.',
      'The question involves autocomplete, word search with a dictionary, or "starts with".',
      'A hash set of full words is too slow because you need partial-match queries.',
    ],
    template: `# Insert a word into a trie of nested dicts.
node = root
for ch in word:
    node = node.setdefault(ch, {})
node['#'] = True  # end-of-word marker`,
    pitfalls: [
      'Forgetting an explicit end-of-word marker, so "app" incorrectly reports as present when only "apple" was inserted.',
      'Rebuilding the trie from scratch per query instead of reusing one built once.',
    ],
  },
  {
    id: 'dsap-graphs',
    name: 'Graphs',
    order: 11,
    signals: [
      'The input is a grid, adjacency list, or edges describing connections.',
      'You need connectivity, shortest unweighted path, or cycle detection.',
      'A dependency ordering (course prerequisites) implies topological sort.',
    ],
    template: `# BFS shortest path / level order on an adjacency list.
from collections import deque
visited = {start}
q = deque([start])
steps = 0
while q:
    for _ in range(len(q)):
        node = q.popleft()
        if node == target:
            return steps
        for nb in graph[node]:
            if nb not in visited:
                visited.add(nb)
                q.append(nb)
    steps += 1
return -1`,
    pitfalls: [
      'Marking a node visited when it is popped instead of when it is enqueued, allowing duplicates in the queue.',
      'Using DFS for shortest-path-in-unweighted-graph problems, which does not guarantee the minimum distance.',
    ],
  },
  {
    id: 'dsap-advanced-graphs',
    name: 'Advanced Graphs',
    order: 12,
    signals: [
      'Edges carry weights and you need shortest path, minimum spanning tree, or a bounded number of stops.',
      'The graph has an ordering constraint that a simple topological sort cannot capture (cycles allowed, weighted).',
      'Union-Find is a better fit than repeated DFS for incremental connectivity queries.',
    ],
    template: `# Dijkstra shortest path with a min-heap.
import heapq
dist = {start: 0}
heap = [(0, start)]
while heap:
    d, node = heapq.heappop(heap)
    if d > dist.get(node, float('inf')):
        continue
    for nb, w in graph[node]:
        nd = d + w
        if nd < dist.get(nb, float('inf')):
            dist[nb] = nd
            heapq.heappush(heap, (nd, nb))
return dist`,
    pitfalls: [
      'Not skipping a stale heap entry when a shorter distance was already found, causing wasted or incorrect relaxations.',
      "Using Dijkstra on a graph with negative edge weights, where it silently gives wrong answers instead of erroring.",
    ],
  },
  {
    id: 'dsap-dp-1d',
    name: '1-D Dynamic Programming',
    order: 13,
    signals: [
      "The answer at position i depends only on a fixed number of previous positions (i-1, i-2, ...).",
      'A recursive brute force has overlapping subproblems indexed by a single integer.',
      'The question asks for a count, min cost, or max value over sequences ending at each index.',
    ],
    template: `# Bottom-up DP where dp[i] depends on dp[i-1] and dp[i-2].
if n <= 1:
    return 1
dp = [0] * (n + 1)
dp[0], dp[1] = 1, 1
for i in range(2, n + 1):
    dp[i] = dp[i - 1] + dp[i - 2]
return dp[n]`,
    pitfalls: [
      'Sizing dp as [0] * (n + 1) and then writing dp[0], dp[1] = 1, 1 without a base-case guard, which throws an IndexError as soon as n is 0.',
      'Off-by-one errors in the base cases, especially dp[0] vs dp[1], that silently shift every later value.',
    ],
  },
  {
    id: 'dsap-dp-2d',
    name: '2-D Dynamic Programming',
    order: 14,
    signals: [
      'You are comparing or combining two sequences (strings, arrays) index by index.',
      'The state needs two indices, like position in string A and position in string B.',
      'A grid problem asks for the number of paths or the min/max cost to reach each cell.',
    ],
    template: `# Longest common subsequence over a 2-D grid of dp states.
m, n = len(a), len(b)
dp = [[0] * (n + 1) for _ in range(m + 1)]
for i in range(1, m + 1):
    for j in range(1, n + 1):
        if a[i - 1] == b[j - 1]:
            dp[i][j] = dp[i - 1][j - 1] + 1
        else:
            dp[i][j] = max(dp[i - 1][j], dp[i][j - 1])
return dp[m][n]`,
    pitfalls: [
      'Allocating the dp grid with shared row references (e.g. [[0]*n]*m), so writing to one row mutates all rows.',
      'Confusing the 1-indexed dp grid with the 0-indexed input strings, off-by-one in the char lookups.',
    ],
  },
  {
    id: 'dsap-greedy',
    name: 'Greedy',
    order: 15,
    signals: [
      'A local optimal choice at each step provably leads to a global optimum.',
      'Sorting the input first, then scanning once, solves the problem.',
      'DP would work but is overkill because no subproblem needs to be revisited.',
    ],
    template: `# Track the farthest reachable index while scanning left to right.
farthest = 0
for i, x in enumerate(nums):
    if i > farthest:
        return False
    farthest = max(farthest, i + x)
return True`,
    pitfalls: [
      'Updating farthest with max(farthest, i + x) but never checking i > farthest first, so the loop walks past a gap it could never have reached and returns the wrong answer instead of failing fast.',
      'Forgetting to sort by the right key (start time vs end time) before the greedy scan.',
    ],
  },
  {
    id: 'dsap-intervals',
    name: 'Intervals',
    order: 16,
    signals: [
      'The input is a list of (start, end) ranges that may overlap.',
      'You need to merge, insert, or count overlaps among ranges.',
      'The question is about scheduling rooms, meetings, or resource conflicts.',
    ],
    template: `# Merge overlapping intervals after sorting by start.
if not intervals:
    return []
intervals.sort(key=lambda iv: iv[0])
merged = [intervals[0]]
for start, end in intervals[1:]:
    if start <= merged[-1][1]:
        merged[-1][1] = max(merged[-1][1], end)
    else:
        merged.append([start, end])
return merged`,
    pitfalls: [
      'Forgetting to sort the intervals first, so the merge scan misses overlaps that are out of order.',
      'Using < instead of <= when checking overlap, mishandling intervals that touch exactly at the boundary.',
      'Indexing intervals[0] to seed merged before checking whether intervals is empty, which throws an IndexError on an empty input.',
    ],
  },
  {
    id: 'dsap-math-geometry',
    name: 'Math & Geometry',
    order: 17,
    signals: [
      'The problem is about matrix rotation, traversal order, or in-place transformation.',
      'You need modular arithmetic, digit manipulation, or careful floating point handling.',
      'Simulating the process directly is feasible and clearer than finding a closed form.',
    ],
    template: `# Rotate an n x n matrix 90 degrees clockwise in place.
n = len(matrix)
for i in range(n):
    for j in range(i + 1, n):
        matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]
for row in matrix:
    row.reverse()`,
    pitfalls: [
      'Allocating a new matrix when the problem requires an in-place transformation.',
      'Transposing and reversing in the wrong order, which rotates counter-clockwise instead of clockwise.',
    ],
  },
  {
    id: 'dsap-bit-manipulation',
    name: 'Bit Manipulation',
    order: 18,
    signals: [
      'The question mentions XOR, AND/OR masks, or counting set bits.',
      'You need O(1) extra space and the input fits in a fixed-width integer.',
      'Finding a single unique element among duplicates hints at XOR cancellation.',
    ],
    template: `# XOR cancels every value that appears twice, leaving the unique one.
result = 0
for x in nums:
    result ^= x
return result`,
    pitfalls: [
      "Assuming Python integers wrap like fixed-width ints, forgetting to mask with 0xFFFFFFFF for 32-bit results.",
      'Returning a masked value like x & 0xFFFFFFFF directly as a negative number without converting back through two’s complement, so a result that should be negative in 32-bit arithmetic instead prints as a large positive Python int.',
    ],
  },
]

export const dsaProblems: DsaProblem[] = [
  // --- Arrays & Hashing (9) ---
  {
    id: 'dsa-217-contains-duplicate',
    patternId: 'dsap-arrays-hashing',
    name: 'Contains Duplicate',
    leetcodeNumber: 217,
    url: 'https://leetcode.com/problems/contains-duplicate/',
    difficulty: 'easy',
    core: true,
    companies: ['meta', 'amazon'],
    minutes: 20,
  },
  {
    id: 'dsa-242-valid-anagram',
    patternId: 'dsap-arrays-hashing',
    name: 'Valid Anagram',
    leetcodeNumber: 242,
    url: 'https://leetcode.com/problems/valid-anagram/',
    difficulty: 'easy',
    core: true,
    companies: ['meta', 'amazon'],
    minutes: 20,
  },
  {
    id: 'dsa-1-two-sum',
    patternId: 'dsap-arrays-hashing',
    name: 'Two Sum',
    leetcodeNumber: 1,
    url: 'https://leetcode.com/problems/two-sum/',
    difficulty: 'easy',
    core: true,
    companies: ['google', 'meta', 'amazon'],
    minutes: 20,
  },
  {
    id: 'dsa-49-group-anagrams',
    patternId: 'dsap-arrays-hashing',
    name: 'Group Anagrams',
    leetcodeNumber: 49,
    url: 'https://leetcode.com/problems/group-anagrams/',
    difficulty: 'medium',
    core: true,
    companies: ['meta'],
    minutes: 30,
  },
  {
    id: 'dsa-347-top-k-frequent-elements',
    patternId: 'dsap-arrays-hashing',
    name: 'Top K Frequent Elements',
    leetcodeNumber: 347,
    url: 'https://leetcode.com/problems/top-k-frequent-elements/',
    difficulty: 'medium',
    core: true,
    companies: ['meta', 'amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-271-encode-and-decode-strings',
    patternId: 'dsap-arrays-hashing',
    name: 'Encode and Decode Strings',
    leetcodeNumber: 271,
    url: 'https://leetcode.com/problems/encode-and-decode-strings/',
    difficulty: 'medium',
    core: true,
    companies: ['meta'],
    minutes: 30,
  },
  {
    id: 'dsa-238-product-of-array-except-self',
    patternId: 'dsap-arrays-hashing',
    name: 'Product of Array Except Self',
    leetcodeNumber: 238,
    url: 'https://leetcode.com/problems/product-of-array-except-self/',
    difficulty: 'medium',
    core: true,
    companies: ['meta', 'amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-36-valid-sudoku',
    patternId: 'dsap-arrays-hashing',
    name: 'Valid Sudoku',
    leetcodeNumber: 36,
    url: 'https://leetcode.com/problems/valid-sudoku/',
    difficulty: 'medium',
    core: false,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-128-longest-consecutive-sequence',
    patternId: 'dsap-arrays-hashing',
    name: 'Longest Consecutive Sequence',
    leetcodeNumber: 128,
    url: 'https://leetcode.com/problems/longest-consecutive-sequence/',
    difficulty: 'medium',
    core: true,
    companies: ['meta'],
    minutes: 30,
  },

  // --- Two Pointers (5) ---
  {
    id: 'dsa-125-valid-palindrome',
    patternId: 'dsap-two-pointers',
    name: 'Valid Palindrome',
    leetcodeNumber: 125,
    url: 'https://leetcode.com/problems/valid-palindrome/',
    difficulty: 'easy',
    core: true,
    companies: ['meta'],
    minutes: 20,
  },
  {
    id: 'dsa-167-two-sum-ii-input-array-is-sorted',
    patternId: 'dsap-two-pointers',
    name: 'Two Sum II',
    leetcodeNumber: 167,
    url: 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/',
    difficulty: 'medium',
    core: false,
    companies: ['meta'],
    minutes: 30,
  },
  {
    id: 'dsa-15-3sum',
    patternId: 'dsap-two-pointers',
    name: '3Sum',
    leetcodeNumber: 15,
    url: 'https://leetcode.com/problems/3sum/',
    difficulty: 'medium',
    core: true,
    companies: ['meta', 'amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-11-container-with-most-water',
    patternId: 'dsap-two-pointers',
    name: 'Container With Most Water',
    leetcodeNumber: 11,
    url: 'https://leetcode.com/problems/container-with-most-water/',
    difficulty: 'medium',
    core: true,
    companies: ['meta', 'amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-42-trapping-rain-water',
    patternId: 'dsap-two-pointers',
    name: 'Trapping Rain Water',
    leetcodeNumber: 42,
    url: 'https://leetcode.com/problems/trapping-rain-water/',
    difficulty: 'hard',
    core: false,
    companies: ['google', 'amazon'],
    minutes: 45,
  },

  // --- Sliding Window (6) ---
  {
    id: 'dsa-121-best-time-to-buy-and-sell-stock',
    patternId: 'dsap-sliding-window',
    name: 'Best Time to Buy and Sell Stock',
    leetcodeNumber: 121,
    url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
    difficulty: 'easy',
    core: true,
    companies: ['meta', 'amazon'],
    minutes: 20,
  },
  {
    id: 'dsa-3-longest-substring-without-repeating-characters',
    patternId: 'dsap-sliding-window',
    name: 'Longest Substring Without Repeating Characters',
    leetcodeNumber: 3,
    url: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
    difficulty: 'medium',
    core: true,
    companies: ['meta', 'amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-424-longest-repeating-character-replacement',
    patternId: 'dsap-sliding-window',
    name: 'Longest Repeating Character Replacement',
    leetcodeNumber: 424,
    url: 'https://leetcode.com/problems/longest-repeating-character-replacement/',
    difficulty: 'medium',
    core: true,
    companies: ['meta'],
    minutes: 30,
  },
  {
    id: 'dsa-567-permutation-in-string',
    patternId: 'dsap-sliding-window',
    name: 'Permutation in String',
    leetcodeNumber: 567,
    url: 'https://leetcode.com/problems/permutation-in-string/',
    difficulty: 'medium',
    core: false,
    companies: ['meta'],
    minutes: 30,
  },
  {
    id: 'dsa-76-minimum-window-substring',
    patternId: 'dsap-sliding-window',
    name: 'Minimum Window Substring',
    leetcodeNumber: 76,
    url: 'https://leetcode.com/problems/minimum-window-substring/',
    difficulty: 'hard',
    core: true,
    companies: ['meta', 'amazon'],
    minutes: 45,
  },
  {
    id: 'dsa-239-sliding-window-maximum',
    patternId: 'dsap-sliding-window',
    name: 'Sliding Window Maximum',
    leetcodeNumber: 239,
    url: 'https://leetcode.com/problems/sliding-window-maximum/',
    difficulty: 'hard',
    core: false,
    companies: ['google', 'amazon'],
    minutes: 45,
  },

  // --- Stack (7) ---
  {
    id: 'dsa-20-valid-parentheses',
    patternId: 'dsap-stack',
    name: 'Valid Parentheses',
    leetcodeNumber: 20,
    url: 'https://leetcode.com/problems/valid-parentheses/',
    difficulty: 'easy',
    core: true,
    companies: ['google', 'meta', 'amazon'],
    minutes: 20,
  },
  {
    id: 'dsa-155-min-stack',
    patternId: 'dsap-stack',
    name: 'Min Stack',
    leetcodeNumber: 155,
    url: 'https://leetcode.com/problems/min-stack/',
    difficulty: 'medium',
    core: false,
    companies: ['amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-150-evaluate-reverse-polish-notation',
    patternId: 'dsap-stack',
    name: 'Evaluate Reverse Polish Notation',
    leetcodeNumber: 150,
    url: 'https://leetcode.com/problems/evaluate-reverse-polish-notation/',
    difficulty: 'medium',
    core: false,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-22-generate-parentheses',
    patternId: 'dsap-stack',
    name: 'Generate Parentheses',
    leetcodeNumber: 22,
    url: 'https://leetcode.com/problems/generate-parentheses/',
    difficulty: 'medium',
    core: false,
    companies: ['meta'],
    minutes: 30,
  },
  {
    id: 'dsa-739-daily-temperatures',
    patternId: 'dsap-stack',
    name: 'Daily Temperatures',
    leetcodeNumber: 739,
    url: 'https://leetcode.com/problems/daily-temperatures/',
    difficulty: 'medium',
    core: false,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-853-car-fleet',
    patternId: 'dsap-stack',
    name: 'Car Fleet',
    leetcodeNumber: 853,
    url: 'https://leetcode.com/problems/car-fleet/',
    difficulty: 'medium',
    core: false,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-84-largest-rectangle-in-histogram',
    patternId: 'dsap-stack',
    name: 'Largest Rectangle in Histogram',
    leetcodeNumber: 84,
    url: 'https://leetcode.com/problems/largest-rectangle-in-histogram/',
    difficulty: 'hard',
    core: false,
    companies: ['google'],
    minutes: 45,
  },

  // --- Binary Search (7) ---
  {
    id: 'dsa-704-binary-search',
    patternId: 'dsap-binary-search',
    name: 'Binary Search',
    leetcodeNumber: 704,
    url: 'https://leetcode.com/problems/binary-search/',
    difficulty: 'easy',
    core: false,
    companies: ['google'],
    minutes: 20,
  },
  {
    id: 'dsa-74-search-a-2d-matrix',
    patternId: 'dsap-binary-search',
    name: 'Search a 2D Matrix',
    leetcodeNumber: 74,
    url: 'https://leetcode.com/problems/search-a-2d-matrix/',
    difficulty: 'medium',
    core: false,
    companies: ['amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-875-koko-eating-bananas',
    patternId: 'dsap-binary-search',
    name: 'Koko Eating Bananas',
    leetcodeNumber: 875,
    url: 'https://leetcode.com/problems/koko-eating-bananas/',
    difficulty: 'medium',
    core: false,
    companies: ['google'],
    minutes: 30,
  },
  {
    id: 'dsa-153-find-minimum-in-rotated-sorted-array',
    patternId: 'dsap-binary-search',
    name: 'Find Minimum in Rotated Sorted Array',
    leetcodeNumber: 153,
    url: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/',
    difficulty: 'medium',
    core: true,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-33-search-in-rotated-sorted-array',
    patternId: 'dsap-binary-search',
    name: 'Search in Rotated Sorted Array',
    leetcodeNumber: 33,
    url: 'https://leetcode.com/problems/search-in-rotated-sorted-array/',
    difficulty: 'medium',
    core: true,
    companies: ['google', 'meta'],
    minutes: 30,
  },
  {
    id: 'dsa-981-time-based-key-value-store',
    patternId: 'dsap-binary-search',
    name: 'Time Based Key-Value Store',
    leetcodeNumber: 981,
    url: 'https://leetcode.com/problems/time-based-key-value-store/',
    difficulty: 'medium',
    core: false,
    companies: ['amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-4-median-of-two-sorted-arrays',
    patternId: 'dsap-binary-search',
    name: 'Median of Two Sorted Arrays',
    leetcodeNumber: 4,
    url: 'https://leetcode.com/problems/median-of-two-sorted-arrays/',
    difficulty: 'hard',
    core: false,
    companies: ['google'],
    minutes: 45,
  },

  // --- Linked List (11) ---
  {
    id: 'dsa-206-reverse-linked-list',
    patternId: 'dsap-linked-list',
    name: 'Reverse Linked List',
    leetcodeNumber: 206,
    url: 'https://leetcode.com/problems/reverse-linked-list/',
    difficulty: 'easy',
    core: true,
    companies: ['amazon'],
    minutes: 20,
  },
  {
    id: 'dsa-21-merge-two-sorted-lists',
    patternId: 'dsap-linked-list',
    name: 'Merge Two Sorted Lists',
    leetcodeNumber: 21,
    url: 'https://leetcode.com/problems/merge-two-sorted-lists/',
    difficulty: 'easy',
    core: true,
    companies: ['amazon'],
    minutes: 20,
  },
  {
    id: 'dsa-143-reorder-list',
    patternId: 'dsap-linked-list',
    name: 'Reorder List',
    leetcodeNumber: 143,
    url: 'https://leetcode.com/problems/reorder-list/',
    difficulty: 'medium',
    core: true,
    companies: ['meta', 'amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-19-remove-nth-node-from-end-of-list',
    patternId: 'dsap-linked-list',
    name: 'Remove Nth Node From End of List',
    leetcodeNumber: 19,
    url: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/',
    difficulty: 'medium',
    core: true,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-138-copy-list-with-random-pointer',
    patternId: 'dsap-linked-list',
    name: 'Copy List With Random Pointer',
    leetcodeNumber: 138,
    url: 'https://leetcode.com/problems/copy-list-with-random-pointer/',
    difficulty: 'medium',
    core: false,
    companies: ['meta'],
    minutes: 30,
  },
  {
    id: 'dsa-2-add-two-numbers',
    patternId: 'dsap-linked-list',
    name: 'Add Two Numbers',
    leetcodeNumber: 2,
    url: 'https://leetcode.com/problems/add-two-numbers/',
    difficulty: 'medium',
    core: false,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-141-linked-list-cycle',
    patternId: 'dsap-linked-list',
    name: 'Linked List Cycle',
    leetcodeNumber: 141,
    url: 'https://leetcode.com/problems/linked-list-cycle/',
    difficulty: 'easy',
    core: true,
    companies: ['amazon'],
    minutes: 20,
  },
  {
    id: 'dsa-287-find-the-duplicate-number',
    patternId: 'dsap-linked-list',
    name: 'Find the Duplicate Number',
    leetcodeNumber: 287,
    url: 'https://leetcode.com/problems/find-the-duplicate-number/',
    difficulty: 'medium',
    core: false,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-146-lru-cache',
    patternId: 'dsap-linked-list',
    name: 'LRU Cache',
    leetcodeNumber: 146,
    url: 'https://leetcode.com/problems/lru-cache/',
    difficulty: 'medium',
    core: false,
    companies: ['amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-23-merge-k-sorted-lists',
    patternId: 'dsap-linked-list',
    name: 'Merge K Sorted Lists',
    leetcodeNumber: 23,
    url: 'https://leetcode.com/problems/merge-k-sorted-lists/',
    difficulty: 'hard',
    core: true,
    companies: ['google'],
    minutes: 45,
  },
  {
    id: 'dsa-25-reverse-nodes-in-k-group',
    patternId: 'dsap-linked-list',
    name: 'Reverse Nodes in K-Group',
    leetcodeNumber: 25,
    url: 'https://leetcode.com/problems/reverse-nodes-in-k-group/',
    difficulty: 'hard',
    core: false,
    companies: ['google'],
    minutes: 45,
  },

  // --- Trees (15) ---
  {
    id: 'dsa-226-invert-binary-tree',
    patternId: 'dsap-trees',
    name: 'Invert Binary Tree',
    leetcodeNumber: 226,
    url: 'https://leetcode.com/problems/invert-binary-tree/',
    difficulty: 'easy',
    core: true,
    companies: ['google', 'meta', 'amazon'],
    minutes: 20,
  },
  {
    id: 'dsa-104-maximum-depth-of-binary-tree',
    patternId: 'dsap-trees',
    name: 'Maximum Depth of Binary Tree',
    leetcodeNumber: 104,
    url: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/',
    difficulty: 'easy',
    core: true,
    companies: ['meta', 'amazon'],
    minutes: 20,
  },
  {
    id: 'dsa-543-diameter-of-binary-tree',
    patternId: 'dsap-trees',
    name: 'Diameter of Binary Tree',
    leetcodeNumber: 543,
    url: 'https://leetcode.com/problems/diameter-of-binary-tree/',
    difficulty: 'easy',
    core: false,
    companies: ['meta'],
    minutes: 20,
  },
  {
    id: 'dsa-110-balanced-binary-tree',
    patternId: 'dsap-trees',
    name: 'Balanced Binary Tree',
    leetcodeNumber: 110,
    url: 'https://leetcode.com/problems/balanced-binary-tree/',
    difficulty: 'easy',
    core: false,
    companies: [],
    minutes: 20,
  },
  {
    id: 'dsa-100-same-tree',
    patternId: 'dsap-trees',
    name: 'Same Tree',
    leetcodeNumber: 100,
    url: 'https://leetcode.com/problems/same-tree/',
    difficulty: 'easy',
    core: true,
    companies: ['meta'],
    minutes: 20,
  },
  {
    id: 'dsa-572-subtree-of-another-tree',
    patternId: 'dsap-trees',
    name: 'Subtree of Another Tree',
    leetcodeNumber: 572,
    url: 'https://leetcode.com/problems/subtree-of-another-tree/',
    difficulty: 'easy',
    core: true,
    companies: ['meta'],
    minutes: 20,
  },
  {
    id: 'dsa-235-lowest-common-ancestor-of-a-binary-search-tree',
    patternId: 'dsap-trees',
    name: 'Lowest Common Ancestor of a BST',
    leetcodeNumber: 235,
    url: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/',
    difficulty: 'medium',
    core: true,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-102-binary-tree-level-order-traversal',
    patternId: 'dsap-trees',
    name: 'Binary Tree Level Order Traversal',
    leetcodeNumber: 102,
    url: 'https://leetcode.com/problems/binary-tree-level-order-traversal/',
    difficulty: 'medium',
    core: true,
    companies: ['meta', 'amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-199-binary-tree-right-side-view',
    patternId: 'dsap-trees',
    name: 'Binary Tree Right Side View',
    leetcodeNumber: 199,
    url: 'https://leetcode.com/problems/binary-tree-right-side-view/',
    difficulty: 'medium',
    core: false,
    companies: ['meta'],
    minutes: 30,
  },
  {
    id: 'dsa-1448-count-good-nodes-in-binary-tree',
    patternId: 'dsap-trees',
    name: 'Count Good Nodes in Binary Tree',
    leetcodeNumber: 1448,
    url: 'https://leetcode.com/problems/count-good-nodes-in-binary-tree/',
    difficulty: 'medium',
    core: false,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-98-validate-binary-search-tree',
    patternId: 'dsap-trees',
    name: 'Validate Binary Search Tree',
    leetcodeNumber: 98,
    url: 'https://leetcode.com/problems/validate-binary-search-tree/',
    difficulty: 'medium',
    core: true,
    companies: ['google', 'amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-230-kth-smallest-element-in-a-bst',
    patternId: 'dsap-trees',
    name: 'Kth Smallest Element in a BST',
    leetcodeNumber: 230,
    url: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/',
    difficulty: 'medium',
    core: true,
    companies: ['amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-105-construct-binary-tree-from-preorder-and-inorder-traversal',
    patternId: 'dsap-trees',
    name: 'Construct Binary Tree from Preorder and Inorder Traversal',
    leetcodeNumber: 105,
    url: 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/',
    difficulty: 'medium',
    core: true,
    companies: ['amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-124-binary-tree-maximum-path-sum',
    patternId: 'dsap-trees',
    name: 'Binary Tree Maximum Path Sum',
    leetcodeNumber: 124,
    url: 'https://leetcode.com/problems/binary-tree-maximum-path-sum/',
    difficulty: 'hard',
    core: true,
    companies: ['google'],
    minutes: 45,
  },
  {
    id: 'dsa-297-serialize-and-deserialize-binary-tree',
    patternId: 'dsap-trees',
    name: 'Serialize and Deserialize Binary Tree',
    leetcodeNumber: 297,
    url: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/',
    difficulty: 'hard',
    core: true,
    companies: ['google', 'meta', 'amazon'],
    minutes: 45,
  },

  // --- Heap / Priority Queue (7) ---
  {
    id: 'dsa-703-kth-largest-element-in-a-stream',
    patternId: 'dsap-heap',
    name: 'Kth Largest Element in a Stream',
    leetcodeNumber: 703,
    url: 'https://leetcode.com/problems/kth-largest-element-in-a-stream/',
    difficulty: 'easy',
    core: false,
    companies: [],
    minutes: 20,
  },
  {
    id: 'dsa-1046-last-stone-weight',
    patternId: 'dsap-heap',
    name: 'Last Stone Weight',
    leetcodeNumber: 1046,
    url: 'https://leetcode.com/problems/last-stone-weight/',
    difficulty: 'easy',
    core: false,
    companies: [],
    minutes: 20,
  },
  {
    id: 'dsa-973-k-closest-points-to-origin',
    patternId: 'dsap-heap',
    name: 'K Closest Points to Origin',
    leetcodeNumber: 973,
    url: 'https://leetcode.com/problems/k-closest-points-to-origin/',
    difficulty: 'medium',
    core: false,
    companies: ['amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-215-kth-largest-element-in-an-array',
    patternId: 'dsap-heap',
    name: 'Kth Largest Element in an Array',
    leetcodeNumber: 215,
    url: 'https://leetcode.com/problems/kth-largest-element-in-an-array/',
    difficulty: 'medium',
    core: false,
    companies: ['google', 'amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-621-task-scheduler',
    patternId: 'dsap-heap',
    name: 'Task Scheduler',
    leetcodeNumber: 621,
    url: 'https://leetcode.com/problems/task-scheduler/',
    difficulty: 'medium',
    core: false,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-355-design-twitter',
    patternId: 'dsap-heap',
    name: 'Design Twitter',
    leetcodeNumber: 355,
    url: 'https://leetcode.com/problems/design-twitter/',
    difficulty: 'medium',
    core: false,
    companies: ['meta', 'amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-295-find-median-from-data-stream',
    patternId: 'dsap-heap',
    name: 'Find Median from Data Stream',
    leetcodeNumber: 295,
    url: 'https://leetcode.com/problems/find-median-from-data-stream/',
    difficulty: 'hard',
    core: true,
    companies: ['google', 'amazon'],
    minutes: 45,
  },

  // --- Backtracking (9) ---
  {
    id: 'dsa-78-subsets',
    patternId: 'dsap-backtracking',
    name: 'Subsets',
    leetcodeNumber: 78,
    url: 'https://leetcode.com/problems/subsets/',
    difficulty: 'medium',
    core: false,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-39-combination-sum',
    patternId: 'dsap-backtracking',
    name: 'Combination Sum',
    leetcodeNumber: 39,
    url: 'https://leetcode.com/problems/combination-sum/',
    difficulty: 'medium',
    core: true,
    companies: ['google'],
    minutes: 30,
  },
  {
    id: 'dsa-40-combination-sum-ii',
    patternId: 'dsap-backtracking',
    name: 'Combination Sum II',
    leetcodeNumber: 40,
    url: 'https://leetcode.com/problems/combination-sum-ii/',
    difficulty: 'medium',
    core: false,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-46-permutations',
    patternId: 'dsap-backtracking',
    name: 'Permutations',
    leetcodeNumber: 46,
    url: 'https://leetcode.com/problems/permutations/',
    difficulty: 'medium',
    core: false,
    companies: ['google', 'meta'],
    minutes: 30,
  },
  {
    id: 'dsa-90-subsets-ii',
    patternId: 'dsap-backtracking',
    name: 'Subsets II',
    leetcodeNumber: 90,
    url: 'https://leetcode.com/problems/subsets-ii/',
    difficulty: 'medium',
    core: false,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-79-word-search',
    patternId: 'dsap-backtracking',
    name: 'Word Search',
    leetcodeNumber: 79,
    url: 'https://leetcode.com/problems/word-search/',
    difficulty: 'medium',
    core: true,
    companies: ['google', 'meta'],
    minutes: 30,
  },
  {
    id: 'dsa-131-palindrome-partitioning',
    patternId: 'dsap-backtracking',
    name: 'Palindrome Partitioning',
    leetcodeNumber: 131,
    url: 'https://leetcode.com/problems/palindrome-partitioning/',
    difficulty: 'medium',
    core: false,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-17-letter-combinations-of-a-phone-number',
    patternId: 'dsap-backtracking',
    name: 'Letter Combinations of a Phone Number',
    leetcodeNumber: 17,
    url: 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/',
    difficulty: 'medium',
    core: false,
    companies: ['meta'],
    minutes: 30,
  },
  {
    id: 'dsa-51-n-queens',
    patternId: 'dsap-backtracking',
    name: 'N-Queens',
    leetcodeNumber: 51,
    url: 'https://leetcode.com/problems/n-queens/',
    difficulty: 'hard',
    core: false,
    companies: ['google'],
    minutes: 45,
  },

  // --- Tries (3) ---
  {
    id: 'dsa-208-implement-trie-prefix-tree',
    patternId: 'dsap-tries',
    name: 'Implement Trie',
    leetcodeNumber: 208,
    url: 'https://leetcode.com/problems/implement-trie-prefix-tree/',
    difficulty: 'medium',
    core: true,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-211-design-add-and-search-words-data-structure',
    patternId: 'dsap-tries',
    name: 'Design Add and Search Words Data Structure',
    leetcodeNumber: 211,
    url: 'https://leetcode.com/problems/design-add-and-search-words-data-structure/',
    difficulty: 'medium',
    core: true,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-212-word-search-ii',
    patternId: 'dsap-tries',
    name: 'Word Search II',
    leetcodeNumber: 212,
    url: 'https://leetcode.com/problems/word-search-ii/',
    difficulty: 'hard',
    core: true,
    companies: ['google', 'amazon'],
    minutes: 45,
  },

  // --- Graphs (13) ---
  {
    id: 'dsa-200-number-of-islands',
    patternId: 'dsap-graphs',
    name: 'Number of Islands',
    leetcodeNumber: 200,
    url: 'https://leetcode.com/problems/number-of-islands/',
    difficulty: 'medium',
    core: true,
    companies: ['google', 'meta', 'amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-695-max-area-of-island',
    patternId: 'dsap-graphs',
    name: 'Max Area of Island',
    leetcodeNumber: 695,
    url: 'https://leetcode.com/problems/max-area-of-island/',
    difficulty: 'medium',
    core: false,
    companies: ['google'],
    minutes: 30,
  },
  {
    id: 'dsa-133-clone-graph',
    patternId: 'dsap-graphs',
    name: 'Clone Graph',
    leetcodeNumber: 133,
    url: 'https://leetcode.com/problems/clone-graph/',
    difficulty: 'medium',
    core: true,
    companies: ['google', 'meta', 'amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-286-walls-and-gates',
    patternId: 'dsap-graphs',
    name: 'Walls and Gates',
    leetcodeNumber: 286,
    url: 'https://leetcode.com/problems/walls-and-gates/',
    difficulty: 'medium',
    core: false,
    companies: ['amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-994-rotting-oranges',
    patternId: 'dsap-graphs',
    name: 'Rotting Oranges',
    leetcodeNumber: 994,
    url: 'https://leetcode.com/problems/rotting-oranges/',
    difficulty: 'medium',
    core: false,
    companies: ['amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-417-pacific-atlantic-water-flow',
    patternId: 'dsap-graphs',
    name: 'Pacific Atlantic Water Flow',
    leetcodeNumber: 417,
    url: 'https://leetcode.com/problems/pacific-atlantic-water-flow/',
    difficulty: 'medium',
    core: true,
    companies: ['google'],
    minutes: 30,
  },
  {
    id: 'dsa-130-surrounded-regions',
    patternId: 'dsap-graphs',
    name: 'Surrounded Regions',
    leetcodeNumber: 130,
    url: 'https://leetcode.com/problems/surrounded-regions/',
    difficulty: 'medium',
    core: false,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-207-course-schedule',
    patternId: 'dsap-graphs',
    name: 'Course Schedule',
    leetcodeNumber: 207,
    url: 'https://leetcode.com/problems/course-schedule/',
    difficulty: 'medium',
    core: true,
    companies: ['google', 'amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-210-course-schedule-ii',
    patternId: 'dsap-graphs',
    name: 'Course Schedule II',
    leetcodeNumber: 210,
    url: 'https://leetcode.com/problems/course-schedule-ii/',
    difficulty: 'medium',
    core: false,
    companies: ['google'],
    minutes: 30,
  },
  {
    id: 'dsa-261-graph-valid-tree',
    patternId: 'dsap-graphs',
    name: 'Graph Valid Tree',
    leetcodeNumber: 261,
    url: 'https://leetcode.com/problems/graph-valid-tree/',
    difficulty: 'medium',
    core: true,
    companies: ['google'],
    minutes: 30,
  },
  {
    id: 'dsa-323-number-of-connected-components-in-an-undirected-graph',
    patternId: 'dsap-graphs',
    name: 'Number of Connected Components in an Undirected Graph',
    leetcodeNumber: 323,
    url: 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/',
    difficulty: 'medium',
    core: true,
    companies: ['google'],
    minutes: 30,
  },
  {
    id: 'dsa-684-redundant-connection',
    patternId: 'dsap-graphs',
    name: 'Redundant Connection',
    leetcodeNumber: 684,
    url: 'https://leetcode.com/problems/redundant-connection/',
    difficulty: 'medium',
    core: false,
    companies: ['google'],
    minutes: 30,
  },
  {
    id: 'dsa-127-word-ladder',
    patternId: 'dsap-graphs',
    name: 'Word Ladder',
    leetcodeNumber: 127,
    url: 'https://leetcode.com/problems/word-ladder/',
    difficulty: 'hard',
    core: false,
    companies: ['google', 'amazon'],
    minutes: 45,
  },

  // --- Advanced Graphs (6) ---
  {
    id: 'dsa-332-reconstruct-itinerary',
    patternId: 'dsap-advanced-graphs',
    name: 'Reconstruct Itinerary',
    leetcodeNumber: 332,
    url: 'https://leetcode.com/problems/reconstruct-itinerary/',
    difficulty: 'hard',
    core: false,
    companies: ['google'],
    minutes: 45,
  },
  {
    id: 'dsa-1584-min-cost-to-connect-all-points',
    patternId: 'dsap-advanced-graphs',
    name: 'Min Cost to Connect All Points',
    leetcodeNumber: 1584,
    url: 'https://leetcode.com/problems/min-cost-to-connect-all-points/',
    difficulty: 'medium',
    core: false,
    companies: ['google'],
    minutes: 30,
  },
  {
    id: 'dsa-743-network-delay-time',
    patternId: 'dsap-advanced-graphs',
    name: 'Network Delay Time',
    leetcodeNumber: 743,
    url: 'https://leetcode.com/problems/network-delay-time/',
    difficulty: 'medium',
    core: false,
    companies: ['google'],
    minutes: 30,
  },
  {
    id: 'dsa-778-swim-in-rising-water',
    patternId: 'dsap-advanced-graphs',
    name: 'Swim in Rising Water',
    leetcodeNumber: 778,
    url: 'https://leetcode.com/problems/swim-in-rising-water/',
    difficulty: 'hard',
    core: false,
    companies: ['google'],
    minutes: 45,
  },
  {
    id: 'dsa-269-alien-dictionary',
    patternId: 'dsap-advanced-graphs',
    name: 'Alien Dictionary',
    leetcodeNumber: 269,
    url: 'https://leetcode.com/problems/alien-dictionary/',
    difficulty: 'hard',
    core: true,
    companies: ['google', 'amazon'],
    minutes: 45,
  },
  {
    id: 'dsa-787-cheapest-flights-within-k-stops',
    patternId: 'dsap-advanced-graphs',
    name: 'Cheapest Flights Within K Stops',
    leetcodeNumber: 787,
    url: 'https://leetcode.com/problems/cheapest-flights-within-k-stops/',
    difficulty: 'medium',
    core: false,
    companies: ['google'],
    minutes: 30,
  },

  // --- 1-D Dynamic Programming (12) ---
  {
    id: 'dsa-70-climbing-stairs',
    patternId: 'dsap-dp-1d',
    name: 'Climbing Stairs',
    leetcodeNumber: 70,
    url: 'https://leetcode.com/problems/climbing-stairs/',
    difficulty: 'easy',
    core: true,
    companies: ['google'],
    minutes: 20,
  },
  {
    id: 'dsa-746-min-cost-climbing-stairs',
    patternId: 'dsap-dp-1d',
    name: 'Min Cost Climbing Stairs',
    leetcodeNumber: 746,
    url: 'https://leetcode.com/problems/min-cost-climbing-stairs/',
    difficulty: 'easy',
    core: false,
    companies: [],
    minutes: 20,
  },
  {
    id: 'dsa-198-house-robber',
    patternId: 'dsap-dp-1d',
    name: 'House Robber',
    leetcodeNumber: 198,
    url: 'https://leetcode.com/problems/house-robber/',
    difficulty: 'medium',
    core: true,
    companies: ['google'],
    minutes: 30,
  },
  {
    id: 'dsa-213-house-robber-ii',
    patternId: 'dsap-dp-1d',
    name: 'House Robber II',
    leetcodeNumber: 213,
    url: 'https://leetcode.com/problems/house-robber-ii/',
    difficulty: 'medium',
    core: true,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-5-longest-palindromic-substring',
    patternId: 'dsap-dp-1d',
    name: 'Longest Palindromic Substring',
    leetcodeNumber: 5,
    url: 'https://leetcode.com/problems/longest-palindromic-substring/',
    difficulty: 'medium',
    core: true,
    companies: ['google', 'meta'],
    minutes: 30,
  },
  {
    id: 'dsa-647-palindromic-substrings',
    patternId: 'dsap-dp-1d',
    name: 'Palindromic Substrings',
    leetcodeNumber: 647,
    url: 'https://leetcode.com/problems/palindromic-substrings/',
    difficulty: 'medium',
    core: true,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-91-decode-ways',
    patternId: 'dsap-dp-1d',
    name: 'Decode Ways',
    leetcodeNumber: 91,
    url: 'https://leetcode.com/problems/decode-ways/',
    difficulty: 'medium',
    core: true,
    companies: ['google', 'amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-322-coin-change',
    patternId: 'dsap-dp-1d',
    name: 'Coin Change',
    leetcodeNumber: 322,
    url: 'https://leetcode.com/problems/coin-change/',
    difficulty: 'medium',
    core: true,
    companies: ['google'],
    minutes: 30,
  },
  {
    id: 'dsa-152-maximum-product-subarray',
    patternId: 'dsap-dp-1d',
    name: 'Maximum Product Subarray',
    leetcodeNumber: 152,
    url: 'https://leetcode.com/problems/maximum-product-subarray/',
    difficulty: 'medium',
    core: true,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-139-word-break',
    patternId: 'dsap-dp-1d',
    name: 'Word Break',
    leetcodeNumber: 139,
    url: 'https://leetcode.com/problems/word-break/',
    difficulty: 'medium',
    core: true,
    companies: ['google', 'meta'],
    minutes: 30,
  },
  {
    id: 'dsa-300-longest-increasing-subsequence',
    patternId: 'dsap-dp-1d',
    name: 'Longest Increasing Subsequence',
    leetcodeNumber: 300,
    url: 'https://leetcode.com/problems/longest-increasing-subsequence/',
    difficulty: 'medium',
    core: true,
    companies: ['google', 'amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-416-partition-equal-subset-sum',
    patternId: 'dsap-dp-1d',
    name: 'Partition Equal Subset Sum',
    leetcodeNumber: 416,
    url: 'https://leetcode.com/problems/partition-equal-subset-sum/',
    difficulty: 'medium',
    core: false,
    companies: [],
    minutes: 30,
  },

  // --- 2-D Dynamic Programming (11) ---
  {
    id: 'dsa-62-unique-paths',
    patternId: 'dsap-dp-2d',
    name: 'Unique Paths',
    leetcodeNumber: 62,
    url: 'https://leetcode.com/problems/unique-paths/',
    difficulty: 'medium',
    core: true,
    companies: ['google'],
    minutes: 30,
  },
  {
    id: 'dsa-1143-longest-common-subsequence',
    patternId: 'dsap-dp-2d',
    name: 'Longest Common Subsequence',
    leetcodeNumber: 1143,
    url: 'https://leetcode.com/problems/longest-common-subsequence/',
    difficulty: 'medium',
    core: true,
    companies: ['google'],
    minutes: 30,
  },
  {
    id: 'dsa-309-best-time-to-buy-and-sell-stock-with-cooldown',
    patternId: 'dsap-dp-2d',
    name: 'Best Time to Buy and Sell Stock with Cooldown',
    leetcodeNumber: 309,
    url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/',
    difficulty: 'medium',
    core: false,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-518-coin-change-ii',
    patternId: 'dsap-dp-2d',
    name: 'Coin Change II',
    leetcodeNumber: 518,
    url: 'https://leetcode.com/problems/coin-change-ii/',
    difficulty: 'medium',
    core: false,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-494-target-sum',
    patternId: 'dsap-dp-2d',
    name: 'Target Sum',
    leetcodeNumber: 494,
    url: 'https://leetcode.com/problems/target-sum/',
    difficulty: 'medium',
    core: false,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-97-interleaving-string',
    patternId: 'dsap-dp-2d',
    name: 'Interleaving String',
    leetcodeNumber: 97,
    url: 'https://leetcode.com/problems/interleaving-string/',
    difficulty: 'medium',
    core: false,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-329-longest-increasing-path-in-a-matrix',
    patternId: 'dsap-dp-2d',
    name: 'Longest Increasing Path in a Matrix',
    leetcodeNumber: 329,
    url: 'https://leetcode.com/problems/longest-increasing-path-in-a-matrix/',
    difficulty: 'hard',
    core: false,
    companies: ['google'],
    minutes: 45,
  },
  {
    id: 'dsa-115-distinct-subsequences',
    patternId: 'dsap-dp-2d',
    name: 'Distinct Subsequences',
    leetcodeNumber: 115,
    url: 'https://leetcode.com/problems/distinct-subsequences/',
    difficulty: 'hard',
    core: false,
    companies: [],
    minutes: 45,
  },
  {
    id: 'dsa-72-edit-distance',
    patternId: 'dsap-dp-2d',
    name: 'Edit Distance',
    leetcodeNumber: 72,
    url: 'https://leetcode.com/problems/edit-distance/',
    difficulty: 'medium',
    core: false,
    companies: ['google', 'meta', 'amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-312-burst-balloons',
    patternId: 'dsap-dp-2d',
    name: 'Burst Balloons',
    leetcodeNumber: 312,
    url: 'https://leetcode.com/problems/burst-balloons/',
    difficulty: 'hard',
    core: false,
    companies: ['google', 'amazon'],
    minutes: 45,
  },
  {
    id: 'dsa-10-regular-expression-matching',
    patternId: 'dsap-dp-2d',
    name: 'Regular Expression Matching',
    leetcodeNumber: 10,
    url: 'https://leetcode.com/problems/regular-expression-matching/',
    difficulty: 'hard',
    core: false,
    companies: ['google', 'amazon'],
    minutes: 45,
  },

  // --- Greedy (8) ---
  {
    id: 'dsa-53-maximum-subarray',
    patternId: 'dsap-greedy',
    name: 'Maximum Subarray',
    leetcodeNumber: 53,
    url: 'https://leetcode.com/problems/maximum-subarray/',
    difficulty: 'medium',
    core: true,
    companies: ['google', 'meta'],
    minutes: 30,
  },
  {
    id: 'dsa-55-jump-game',
    patternId: 'dsap-greedy',
    name: 'Jump Game',
    leetcodeNumber: 55,
    url: 'https://leetcode.com/problems/jump-game/',
    difficulty: 'medium',
    core: true,
    companies: ['amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-45-jump-game-ii',
    patternId: 'dsap-greedy',
    name: 'Jump Game II',
    leetcodeNumber: 45,
    url: 'https://leetcode.com/problems/jump-game-ii/',
    difficulty: 'medium',
    core: false,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-134-gas-station',
    patternId: 'dsap-greedy',
    name: 'Gas Station',
    leetcodeNumber: 134,
    url: 'https://leetcode.com/problems/gas-station/',
    difficulty: 'medium',
    core: false,
    companies: ['amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-1296-divide-array-in-sets-of-k-consecutive-numbers',
    patternId: 'dsap-greedy',
    name: 'Hand of Straights',
    leetcodeNumber: 1296,
    url: 'https://leetcode.com/problems/divide-array-in-sets-of-k-consecutive-numbers/',
    difficulty: 'medium',
    core: false,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-1899-merge-triplets-to-form-target-triplet',
    patternId: 'dsap-greedy',
    name: 'Merge Triplets to Form Target Triplet',
    leetcodeNumber: 1899,
    url: 'https://leetcode.com/problems/merge-triplets-to-form-target-triplet/',
    difficulty: 'medium',
    core: false,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-763-partition-labels',
    patternId: 'dsap-greedy',
    name: 'Partition Labels',
    leetcodeNumber: 763,
    url: 'https://leetcode.com/problems/partition-labels/',
    difficulty: 'medium',
    core: false,
    companies: ['meta'],
    minutes: 30,
  },
  {
    id: 'dsa-678-valid-parenthesis-string',
    patternId: 'dsap-greedy',
    name: 'Valid Parenthesis String',
    leetcodeNumber: 678,
    url: 'https://leetcode.com/problems/valid-parenthesis-string/',
    difficulty: 'medium',
    core: false,
    companies: [],
    minutes: 30,
  },

  // --- Intervals (6) ---
  {
    id: 'dsa-57-insert-interval',
    patternId: 'dsap-intervals',
    name: 'Insert Interval',
    leetcodeNumber: 57,
    url: 'https://leetcode.com/problems/insert-interval/',
    difficulty: 'medium',
    core: true,
    companies: ['amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-56-merge-intervals',
    patternId: 'dsap-intervals',
    name: 'Merge Intervals',
    leetcodeNumber: 56,
    url: 'https://leetcode.com/problems/merge-intervals/',
    difficulty: 'medium',
    core: true,
    companies: ['google', 'meta', 'amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-435-non-overlapping-intervals',
    patternId: 'dsap-intervals',
    name: 'Non-overlapping Intervals',
    leetcodeNumber: 435,
    url: 'https://leetcode.com/problems/non-overlapping-intervals/',
    difficulty: 'medium',
    core: true,
    companies: ['amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-252-meeting-rooms',
    patternId: 'dsap-intervals',
    name: 'Meeting Rooms',
    leetcodeNumber: 252,
    url: 'https://leetcode.com/problems/meeting-rooms/',
    difficulty: 'easy',
    core: true,
    companies: ['meta', 'amazon'],
    minutes: 20,
  },
  {
    id: 'dsa-253-meeting-rooms-ii',
    patternId: 'dsap-intervals',
    name: 'Meeting Rooms II',
    leetcodeNumber: 253,
    url: 'https://leetcode.com/problems/meeting-rooms-ii/',
    difficulty: 'medium',
    core: true,
    companies: ['amazon'],
    minutes: 30,
  },
  {
    id: 'dsa-1851-minimum-interval-to-include-each-query',
    patternId: 'dsap-intervals',
    name: 'Minimum Interval to Include Each Query',
    leetcodeNumber: 1851,
    url: 'https://leetcode.com/problems/minimum-interval-to-include-each-query/',
    difficulty: 'hard',
    core: false,
    companies: [],
    minutes: 45,
  },

  // --- Math & Geometry (8) ---
  {
    id: 'dsa-48-rotate-image',
    patternId: 'dsap-math-geometry',
    name: 'Rotate Image',
    leetcodeNumber: 48,
    url: 'https://leetcode.com/problems/rotate-image/',
    difficulty: 'medium',
    core: true,
    companies: ['meta'],
    minutes: 30,
  },
  {
    id: 'dsa-54-spiral-matrix',
    patternId: 'dsap-math-geometry',
    name: 'Spiral Matrix',
    leetcodeNumber: 54,
    url: 'https://leetcode.com/problems/spiral-matrix/',
    difficulty: 'medium',
    core: true,
    companies: ['meta'],
    minutes: 30,
  },
  {
    id: 'dsa-73-set-matrix-zeroes',
    patternId: 'dsap-math-geometry',
    name: 'Set Matrix Zeroes',
    leetcodeNumber: 73,
    url: 'https://leetcode.com/problems/set-matrix-zeroes/',
    difficulty: 'medium',
    core: true,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-202-happy-number',
    patternId: 'dsap-math-geometry',
    name: 'Happy Number',
    leetcodeNumber: 202,
    url: 'https://leetcode.com/problems/happy-number/',
    difficulty: 'easy',
    core: false,
    companies: [],
    minutes: 20,
  },
  {
    id: 'dsa-66-plus-one',
    patternId: 'dsap-math-geometry',
    name: 'Plus One',
    leetcodeNumber: 66,
    url: 'https://leetcode.com/problems/plus-one/',
    difficulty: 'easy',
    core: false,
    companies: ['amazon'],
    minutes: 20,
  },
  {
    id: 'dsa-50-powx-n',
    patternId: 'dsap-math-geometry',
    name: 'Pow(x, n)',
    leetcodeNumber: 50,
    url: 'https://leetcode.com/problems/powx-n/',
    difficulty: 'medium',
    core: false,
    companies: ['google'],
    minutes: 30,
  },
  {
    id: 'dsa-43-multiply-strings',
    patternId: 'dsap-math-geometry',
    name: 'Multiply Strings',
    leetcodeNumber: 43,
    url: 'https://leetcode.com/problems/multiply-strings/',
    difficulty: 'medium',
    core: false,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-2013-detect-squares',
    patternId: 'dsap-math-geometry',
    name: 'Detect Squares',
    leetcodeNumber: 2013,
    url: 'https://leetcode.com/problems/detect-squares/',
    difficulty: 'medium',
    core: false,
    companies: [],
    minutes: 30,
  },

  // --- Bit Manipulation (7) ---
  {
    id: 'dsa-136-single-number',
    patternId: 'dsap-bit-manipulation',
    name: 'Single Number',
    leetcodeNumber: 136,
    url: 'https://leetcode.com/problems/single-number/',
    difficulty: 'easy',
    core: false,
    companies: ['meta'],
    minutes: 20,
  },
  {
    id: 'dsa-191-number-of-1-bits',
    patternId: 'dsap-bit-manipulation',
    name: 'Number of 1 Bits',
    leetcodeNumber: 191,
    url: 'https://leetcode.com/problems/number-of-1-bits/',
    difficulty: 'easy',
    core: true,
    companies: ['google'],
    minutes: 20,
  },
  {
    id: 'dsa-338-counting-bits',
    patternId: 'dsap-bit-manipulation',
    name: 'Counting Bits',
    leetcodeNumber: 338,
    url: 'https://leetcode.com/problems/counting-bits/',
    difficulty: 'easy',
    core: true,
    companies: [],
    minutes: 20,
  },
  {
    id: 'dsa-190-reverse-bits',
    patternId: 'dsap-bit-manipulation',
    name: 'Reverse Bits',
    leetcodeNumber: 190,
    url: 'https://leetcode.com/problems/reverse-bits/',
    difficulty: 'easy',
    core: true,
    companies: [],
    minutes: 20,
  },
  {
    id: 'dsa-268-missing-number',
    patternId: 'dsap-bit-manipulation',
    name: 'Missing Number',
    leetcodeNumber: 268,
    url: 'https://leetcode.com/problems/missing-number/',
    difficulty: 'easy',
    core: true,
    companies: ['amazon'],
    minutes: 20,
  },
  {
    id: 'dsa-371-sum-of-two-integers',
    patternId: 'dsap-bit-manipulation',
    name: 'Sum of Two Integers',
    leetcodeNumber: 371,
    url: 'https://leetcode.com/problems/sum-of-two-integers/',
    difficulty: 'medium',
    core: true,
    companies: [],
    minutes: 30,
  },
  {
    id: 'dsa-7-reverse-integer',
    patternId: 'dsap-bit-manipulation',
    name: 'Reverse Integer',
    leetcodeNumber: 7,
    url: 'https://leetcode.com/problems/reverse-integer/',
    difficulty: 'medium',
    core: false,
    companies: [],
    minutes: 30,
  },
]
