import type { Reading } from '@/lib/content/schema'

export const readings: Reading[] = [
  // Week 1
  {
    id: 'read-rag-2020',
    weekId: 'week-01',
    kind: 'paper',
    title: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
    source: 'Lewis et al., Meta AI',
    year: 2020,
    url: 'https://arxiv.org/abs/2005.11401',
    why: 'The paper that named RAG. Read it to see what the original architecture did and did not claim, before you build your own version of it this week.',
    minutes: 35,
  },
  {
    id: 'read-anthropic-contextual-retrieval',
    weekId: 'week-01',
    kind: 'post',
    title: 'Introducing Contextual Retrieval',
    source: 'Anthropic',
    year: 2024,
    url: 'https://www.anthropic.com/engineering/contextual-retrieval',
    why: 'Shows a concrete, production-tested fix for chunks that lose context, which directly informs how you design chunking in ms-rag-1 this week.',
    minutes: 25,
  },
  {
    id: 'read-api-claude-fable-5-1',
    weekId: 'week-01',
    kind: 'api',
    title: 'Claude Fable 5.1',
    source: 'Anthropic',
    year: 2026,
    url: 'https://www.anthropic.com/claude-fable-and-mythos-5-1',
    why: "Anthropic's current frontier model, already shipping on the API. Skim the launch page for context limits and pricing before you pick a generator this week.",
    minutes: 10,
  },
  {
    id: 'read-api-gpt-6-astra',
    weekId: 'week-01',
    kind: 'api',
    title: 'GPT-6 Astra',
    source: 'OpenAI',
    year: 2026,
    url: 'https://openai.com/index/gpt-6-astra/',
    why: 'A second frontier model available now for the generator slot in your RAG stack. Compare its context window and pricing against Claude before you commit.',
    minutes: 10,
  },
  {
    id: 'read-api-gemini-3-8-flash',
    weekId: 'week-01',
    kind: 'api',
    title: 'Gemini 3.8 Flash',
    source: 'Google',
    year: 2026,
    url: 'https://blog.google/innovation-and-ai/models-and-research/gemini-models/3-8-flash-and-3-8-flash-cyber/',
    why: 'A fast, low-cost model already available from Google, useful once ms-rag-3 later this month needs a cheap model for query rewriting and reranking experiments.',
    minutes: 10,
  },

  // Week 2
  {
    id: 'read-lost-in-the-middle',
    weekId: 'week-02',
    kind: 'paper',
    title: 'Lost in the Middle: How Language Models Use Long Contexts',
    source: 'Liu et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2307.03172',
    why: 'Explains why stuffing more retrieved chunks into the prompt can hurt answer quality, which shapes how you order context in this week\'s hybrid retrieval work.',
    minutes: 35,
  },
  {
    id: 'read-bert-reranking',
    weekId: 'week-02',
    kind: 'paper',
    title: 'Passage Re-ranking with BERT',
    source: 'Nogueira and Cho',
    year: 2019,
    url: 'https://arxiv.org/abs/1901.04085',
    why: 'The original cross-encoder reranking recipe you are implementing this week in ms-rag-2, including why reranking beats retrieval scores alone.',
    minutes: 35,
  },

  // Week 3
  {
    id: 'read-ragas',
    weekId: 'week-03',
    kind: 'paper',
    title: 'RAGAS: Automated Evaluation of Retrieval Augmented Generation',
    source: 'Es et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2309.15217',
    why: 'Gives you the reference-free metrics for faithfulness and relevance you need this week to build the eval harness module in ms-rag-3.',
    minutes: 35,
  },
  {
    id: 'read-seven-failure-points',
    weekId: 'week-03',
    kind: 'paper',
    title: 'Seven Failure Points When Engineering a Retrieval Augmented Generation System',
    source: 'Barnett et al.',
    year: 2024,
    url: 'https://arxiv.org/abs/2401.05856',
    why: 'A field-tested taxonomy of what actually breaks in RAG systems, which you use this week to design the ablation cases for your eval harness.',
    minutes: 35,
  },

  // Week 4
  {
    id: 'read-prompt-injection',
    weekId: 'week-04',
    kind: 'paper',
    title: "Not What You've Signed Up For: Compromising Real-World LLM-Integrated Applications with Indirect Prompt Injection",
    source: 'Greshake et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2302.12173',
    why: 'Documents how instructions hidden in retrieved documents hijack an LLM, the exact threat model your guardrail layer in ms-rag-4 must defend against this week.',
    minutes: 35,
  },
  {
    id: 'read-self-rag',
    weekId: 'week-04',
    kind: 'paper',
    title: 'Self-RAG: Learning to Retrieve, Generate, and Critique through Self-Reflection',
    source: 'Asai et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2310.11511',
    why: 'Shows a model deciding when to retrieve and self-critiquing its answer, directly relevant to the RAG-vs-fine-tuning defense question you close month 1 with.',
    minutes: 35,
  },

  // Week 5 (month 2, proj-advanced-rag: embeddings / retrieval theory)
  {
    id: 'read-mteb',
    weekId: 'week-05',
    kind: 'paper',
    title: 'MTEB: Massive Text Embedding Benchmark',
    source: 'Muennighoff et al.',
    year: 2022,
    url: 'https://arxiv.org/abs/2210.07316',
    why: 'Gives you a principled way to pick an embedding model for the parent-document and hierarchical chunk store this week\'s ms-advanced-rag-2 asks you to build.',
    minutes: 35,
  },
  {
    id: 'read-api-claude-opus-5',
    weekId: 'week-05',
    kind: 'api',
    title: 'Claude Opus 5 with the effort dial',
    source: 'Anthropic',
    year: 2026,
    url: 'https://www.anthropic.com/news/claude-opus-5',
    why: "Anthropic's effort-dial release, live now on the API. It changes the cost-quality tradeoff for the retrieval planner you are building this week in ms-advanced-rag-1.",
    minutes: 10,
  },

  // Week 6 (month 2: BM25/retrieval theory, agentic retrieval reasoning)
  {
    id: 'read-ir-book-bm25-eval',
    weekId: 'week-06',
    kind: 'post',
    title: 'Introduction to Information Retrieval: BM25 and evaluation chapters',
    source: 'Manning, Raghavan, and Schütze',
    year: 2008,
    url: 'https://nlp.stanford.edu/IR-book/',
    why: 'Grounds the BM25 half of your hybrid retriever and the evaluation metrics you reuse for the structured/unstructured router this week, in first-principles detail.',
    minutes: 25,
  },
  {
    id: 'read-api-glm-5-3',
    weekId: 'week-06',
    kind: 'api',
    title: 'GLM-5.3',
    source: 'Z.AI',
    year: 2026,
    url: 'https://z.ai/blog/glm-5.3',
    why: "Z.ai's frontier coding and agentic model, released and available on the API now; worth benchmarking as the router's cheap path since routing decisions live or die on unit economics.",
    minutes: 10,
  },

  // Week 7 (month 2: prompting techniques feed the query-rewriting / adaptive-retrieval milestone)
  {
    id: 'read-prompt-report',
    weekId: 'week-07',
    kind: 'paper',
    title: 'The Prompt Report: A Systematic Survey of Prompting Techniques',
    source: 'Schulhoff et al.',
    year: 2024,
    url: 'https://arxiv.org/abs/2406.06608',
    why: 'A vocabulary and taxonomy for prompting techniques, useful this week for designing the metadata-filter and routing prompts in ms-advanced-rag-3.',
    minutes: 35,
  },
  {
    id: 'read-api-deepseek-v4-flash-vision',
    weekId: 'week-07',
    kind: 'api',
    title: 'DeepSeek V4 Flash Vision',
    source: 'DeepSeek',
    year: 2026,
    url: 'https://api-docs.deepseek.com/news/news260821/',
    why: "DeepSeek's multimodal model, live on the API now; adds vision to the V4-Flash line, useful once this week's red-team eval set covers documents with embedded images.",
    minutes: 10,
  },

  // Week 8 (month 2 wrap-up: production RAG patterns, hardened guardrails)
  {
    id: 'read-eugene-yan-llm-patterns',
    weekId: 'week-08',
    kind: 'post',
    title: 'Patterns for Building LLM-based Systems and Products',
    source: 'Eugene Yan',
    year: 2023,
    url: 'https://eugeneyan.com/writing/llm-patterns/',
    why: "A practitioner's checklist of retrieval, caching, and guardrail patterns that maps directly onto the hardened-guardrail red-team milestone you close month 2 with.",
    minutes: 25,
  },
  {
    id: 'read-api-qwen-3-8',
    weekId: 'week-08',
    kind: 'api',
    title: 'Qwen 3.8',
    source: 'Alibaba',
    year: 2026,
    url: 'https://qwen.ai/blog?id=qwen3.8',
    why: "Alibaba's newest open-weight flagship, already released with open weights; worth benchmarking for on-prem or cost-sensitive deployments as you wrap up month 2 this week.",
    minutes: 10,
  },

  // Week 9 (month 3 opens, proj-graph-rag)
  {
    id: 'read-graphrag',
    weekId: 'week-09',
    kind: 'paper',
    title: 'From Local to Global: A Graph RAG Approach to Query-Focused Summarization',
    source: 'Edge et al., Microsoft',
    year: 2024,
    url: 'https://arxiv.org/abs/2404.16130',
    why: 'The design this month\'s ms-graph-rag-1 entity-and-relation extraction pipeline builds toward, so read it now before you start extraction.',
    minutes: 35,
  },

  // Week 10 (month 3, ms-graph-rag-1: entity/relation extraction pipeline)
  {
    id: 'read-kg-construction-survey',
    weekId: 'week-10',
    kind: 'paper',
    title: 'A Comprehensive Survey on Automatic Knowledge Graph Construction',
    source: 'Zhong et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2302.05019',
    why: 'Maps the acquisition, refinement, and evolution steps of building a knowledge graph from text, the exact pipeline ms-graph-rag-1 asks you to build this week.',
    minutes: 35,
  },
  {
    id: 'read-rebel-relation-extraction',
    weekId: 'week-10',
    kind: 'paper',
    title: 'REBEL: Relation Extraction By End-to-end Language Generation',
    source: 'Huguet Cabot and Navigli',
    year: 2021,
    url: 'https://aclanthology.org/2021.findings-emnlp.204/',
    why: 'A concrete seq2seq recipe for joint entity and relation extraction over 200+ relation types, directly usable for the extraction pipeline in ms-graph-rag-1 this week.',
    minutes: 35,
  },

  // Week 11 (month 3, ms-graph-rag-2: graph construction and community detection)
  {
    id: 'read-leiden-community-detection',
    weekId: 'week-11',
    kind: 'paper',
    title: 'From Louvain to Leiden: Guaranteeing Well-Connected Communities',
    source: 'Traag, Waltman, and van Eck',
    year: 2019,
    url: 'https://arxiv.org/abs/1810.08473',
    why: 'The community detection algorithm ms-graph-rag-2 needs this week; Louvain can leave communities disconnected, and this is the fix you should use instead.',
    minutes: 35,
  },
  {
    id: 'read-raptor',
    weekId: 'week-11',
    kind: 'paper',
    title: 'RAPTOR: Recursive Abstractive Processing for Tree-Organized Retrieval',
    source: 'Sarthi et al.',
    year: 2024,
    url: 'https://arxiv.org/abs/2401.18059',
    why: 'Shows how to recursively cluster and summarize chunks into a tree, the pattern to follow for the community summaries ms-graph-rag-2 asks for this week.',
    minutes: 35,
  },

  // Week 12 (month 3, ms-graph-rag-3: graph plus vector hybrid retrieval)
  {
    id: 'read-hipporag',
    weekId: 'week-12',
    kind: 'paper',
    title: 'HippoRAG: Neurobiologically Inspired Long-Term Memory for Large Language Models',
    source: 'Gutiérrez et al.',
    year: 2024,
    url: 'https://arxiv.org/abs/2405.14831',
    why: 'Combines a knowledge graph with personalized PageRank over embeddings, a concrete design for the graph-plus-vector hybrid retriever ms-graph-rag-3 asks you to build this week.',
    minutes: 35,
  },
  {
    id: 'read-lightrag',
    weekId: 'week-12',
    kind: 'paper',
    title: 'LightRAG: Simple and Fast Retrieval-Augmented Generation',
    source: 'Guo et al.',
    year: 2024,
    url: 'https://arxiv.org/abs/2410.05779',
    why: 'A dual-level (graph plus vector) retrieval design lighter than full GraphRAG, worth comparing against your own ms-graph-rag-3 hybrid retriever this week.',
    minutes: 35,
  },

  // Week 13 (month 3 close, ms-graph-rag-4: comparative eval against month 2)
  {
    id: 'read-rag-vs-graphrag-eval',
    weekId: 'week-13',
    kind: 'paper',
    title: 'RAG vs. GraphRAG: A Systematic Evaluation and Key Insights',
    source: 'Han et al.',
    year: 2025,
    url: 'https://arxiv.org/abs/2502.11371',
    why: 'A published protocol for comparing vector RAG against graph RAG on global and local questions, the exact comparison ms-graph-rag-4 asks you to write up this week.',
    minutes: 35,
  },

  // Week 14 (month 4 opens, proj-agents: tool layer, planner/workers, memory)
  {
    id: 'read-react',
    weekId: 'week-14',
    kind: 'paper',
    title: 'ReAct: Synergizing Reasoning and Acting in Language Models',
    source: 'Yao et al.',
    year: 2022,
    url: 'https://arxiv.org/abs/2210.03629',
    why: 'The reason-then-act loop underlies the planner-plus-workers design ms-agents-2 asks you to build this week.',
    minutes: 35,
  },
  {
    id: 'read-memgpt',
    weekId: 'week-14',
    kind: 'paper',
    title: 'MemGPT: Towards LLMs as Operating Systems',
    source: 'Packer et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2310.08560',
    why: 'Introduces the tiered short-term/long-term memory design you need this week to give your worker agents memory in ms-agents-2.',
    minutes: 35,
  },

  // Week 15 (month 4: agent workflow patterns and human approval)
  {
    id: 'read-building-effective-agents',
    weekId: 'week-15',
    kind: 'post',
    title: 'Building Effective Agents',
    source: 'Anthropic',
    year: 2024,
    url: 'https://www.anthropic.com/engineering/building-effective-agents',
    why: 'Lays out the routing and human-in-the-loop patterns you apply directly this week when building the approval flow and audit log in ms-agents-3.',
    minutes: 25,
  },
  {
    id: 'read-lilian-weng-agents',
    weekId: 'week-15',
    kind: 'post',
    title: 'LLM Powered Autonomous Agents',
    source: 'Lilian Weng',
    year: 2023,
    url: 'https://lilianweng.github.io/posts/2023-06-23-agent/',
    why: 'A clear map of planning, memory, and tool-use components, useful this week for reviewing your approval flow and audit log design in ms-agents-3.',
    minutes: 25,
  },

  // Week 16 (month 4: agent reasoning and eval suite)
  {
    id: 'read-chain-of-thought',
    weekId: 'week-16',
    kind: 'paper',
    title: 'Chain-of-Thought Prompting Elicits Reasoning in Large Language Models',
    source: 'Wei et al.',
    year: 2022,
    url: 'https://arxiv.org/abs/2201.11903',
    why: 'The reasoning technique your planner can use to explain a plan before acting, useful this week while you build the task-success eval suite in ms-agents-4.',
    minutes: 35,
  },
  {
    id: 'read-swe-bench',
    weekId: 'week-16',
    kind: 'paper',
    title: 'SWE-bench: Can Language Models Resolve Real-World GitHub Issues?',
    source: 'Jimenez et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2310.06770',
    why: 'A benchmark design worth studying for how it grades task success on real, messy work, a pattern to borrow for the eval suite in ms-agents-4 this week.',
    minutes: 35,
  },

  // Week 17 (month 4 close: eval suite, cost controls, model routing)
  {
    id: 'read-ifeval',
    weekId: 'week-17',
    kind: 'paper',
    title: 'Instruction-Following Evaluation for Large Language Models (IFEval)',
    source: 'Zhou et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2311.07911',
    why: 'Gives you verifiable, rule-based instruction-following checks to add alongside task-success scoring in this week\'s ms-agents-4 eval suite.',
    minutes: 35,
  },

  // Week 18 (month 5 opens, proj-gpt-from-scratch: tokenizer through training loop)
  {
    id: 'read-attention-is-all-you-need',
    weekId: 'week-18',
    kind: 'paper',
    title: 'Attention Is All You Need',
    source: 'Vaswani et al.',
    year: 2017,
    url: 'https://arxiv.org/abs/1706.03762',
    why: 'The transformer architecture you are implementing block by block this week in ms-gpt-from-scratch-1; re-read it as the blueprint for your build.',
    minutes: 35,
  },
  {
    id: 'read-chinchilla',
    weekId: 'week-18',
    kind: 'paper',
    title: 'Training Compute-Optimal Large Language Models',
    source: 'Hoffmann et al.',
    year: 2022,
    url: 'https://arxiv.org/abs/2203.15556',
    why: 'The compute-optimal scaling law that should inform how you size your model and data for the training run in ms-gpt-from-scratch-1 this week.',
    minutes: 35,
  },

  // Week 19 (month 5: pretraining scale and RoPE swap-in)
  {
    id: 'read-scaling-laws',
    weekId: 'week-19',
    kind: 'paper',
    title: 'Scaling Laws for Neural Language Models',
    source: 'Kaplan et al.',
    year: 2020,
    url: 'https://arxiv.org/abs/2001.08361',
    why: 'The original scaling-law paper, useful alongside Chinchilla for judging whether your loss curves this week look healthy before you swap in RoPE.',
    minutes: 35,
  },
  {
    id: 'read-rope',
    weekId: 'week-19',
    kind: 'paper',
    title: 'RoFormer: Enhanced Transformer with Rotary Position Embedding',
    source: 'Su et al.',
    year: 2021,
    url: 'https://arxiv.org/abs/2104.09864',
    why: 'RoPE is the first component ms-gpt-from-scratch-2 swaps in this week, so read the derivation before you implement it.',
    minutes: 35,
  },

  // Week 20 (month 5: GQA and FlashAttention, still ms-gpt-from-scratch-2)
  {
    id: 'read-gqa',
    weekId: 'week-20',
    kind: 'paper',
    title: 'GQA: Training Generalized Multi-Query Transformer Models from Multi-Head Checkpoints',
    source: 'Ainslie et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2305.13245',
    why: 'Explains the KV-cache savings from grouped-query attention, the second component ms-gpt-from-scratch-2 measures this week against your multi-head baseline.',
    minutes: 35,
  },
  {
    id: 'read-flashattention',
    weekId: 'week-20',
    kind: 'paper',
    title: 'FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness',
    source: 'Dao et al.',
    year: 2022,
    url: 'https://arxiv.org/abs/2205.14135',
    why: 'The IO-aware attention kernel that speeds up the training and measurement pass ms-gpt-from-scratch-2 asks for this week.',
    minutes: 35,
  },

  // Week 21 (month 5: KV cache, batching, streaming server)
  {
    id: 'read-vllm-pagedattention',
    weekId: 'week-21',
    kind: 'paper',
    title: 'Efficient Memory Management for Large Language Model Serving with PagedAttention',
    source: 'Kwon et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2309.06180',
    why: 'The KV-cache memory management scheme directly relevant to the KV cache and batched generation ms-gpt-from-scratch-3 asks you to build this week.',
    minutes: 35,
  },
  {
    id: 'read-speculative-decoding',
    weekId: 'week-21',
    kind: 'paper',
    title: 'Fast Inference from Transformers via Speculative Decoding',
    source: 'Leviathan et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2211.17192',
    why: 'A decode-time speedup technique to consider for the throughput numbers your streaming server milestone needs to report next week.',
    minutes: 35,
  },

  // Week 22 (month 5 close, ms-gpt-from-scratch-4: streaming server, throughput/latency)
  {
    id: 'read-gptq-quantization',
    weekId: 'week-22',
    kind: 'paper',
    title: 'GPTQ: Accurate Post-Training Quantization for Generative Pre-trained Transformers',
    source: 'Frantar et al.',
    year: 2022,
    url: 'https://arxiv.org/abs/2210.17323',
    why: 'A one-shot weight quantization method that cuts memory and cost with little accuracy loss, worth applying to the streaming server ms-gpt-from-scratch-4 asks you to measure this week.',
    minutes: 35,
  },

  // Week 23 (month 6 opens, proj-fine-tune-eval: dataset curation, LoRA SFT)
  {
    id: 'read-lora',
    weekId: 'week-23',
    kind: 'paper',
    title: 'LoRA: Low-Rank Adaptation of Large Language Models',
    source: 'Hu et al.',
    year: 2021,
    url: 'https://arxiv.org/abs/2106.09685',
    why: 'The parameter-efficient fine-tuning method ms-fine-tune-eval-2 asks you to run this week, worth reading in full before you set rank and target modules.',
    minutes: 35,
  },
  {
    id: 'read-qlora',
    weekId: 'week-23',
    kind: 'paper',
    title: 'QLoRA: Efficient Finetuning of Quantized LLMs',
    source: 'Dettmers et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2305.14314',
    why: 'Shows how quantization keeps LoRA fine-tuning affordable on a single GPU, the budget constraint ms-fine-tune-eval-2 has to respect this week.',
    minutes: 35,
  },

  // Week 24 (month 6: preference data and DPO)
  {
    id: 'read-dpo',
    weekId: 'week-24',
    kind: 'paper',
    title: 'Direct Preference Optimization: Your Language Model is Secretly a Reward Model',
    source: 'Rafailov et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2305.18290',
    why: 'The preference-tuning method ms-fine-tune-eval-3 asks you to run this week on top of your SFT model, so read the derivation before you train.',
    minutes: 35,
  },
  {
    id: 'read-deepseek-r1',
    weekId: 'week-24',
    kind: 'paper',
    title: 'DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning',
    source: 'DeepSeek AI',
    year: 2025,
    url: 'https://arxiv.org/abs/2501.12948',
    why: 'Shows reinforcement learning producing reasoning behavior directly, a useful contrast to the DPO run you are doing this week in ms-fine-tune-eval-3.',
    minutes: 35,
  },

  // Week 25 (month 6: comparative eval report)
  {
    id: 'read-mt-bench-judge',
    weekId: 'week-25',
    kind: 'paper',
    title: 'Judging LLM-as-a-Judge with MT-Bench and Chatbot Arena',
    source: 'Zheng et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2306.05685',
    why: 'Documents the biases of LLM-as-judge scoring you should account for before trusting the comparative eval report ms-fine-tune-eval-4 asks for this week.',
    minutes: 35,
  },

  // Week 26 (month 6 close: comparative eval report and the interview sprint)
  {
    id: 'read-constitutional-ai',
    weekId: 'week-26',
    kind: 'paper',
    title: 'Constitutional AI: Harmlessness from AI Feedback',
    source: 'Bai et al., Anthropic',
    year: 2022,
    url: 'https://arxiv.org/abs/2212.08073',
    why: 'Lays out RLAIF as an alternative to human-labeled RLHF, direct ammunition for the "DPO vs RLHF, what did you trade away" defense question you close ms-fine-tune-eval-4 with this week.',
    minutes: 35,
  },
]
