import type { Reading } from '@/lib/content/schema'

export const readings: Reading[] = [
  // Week 1
  {
    id: 'read-rag-2020',
    weekId: 'week-01',
    kind: 'paper',
    title: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
    source: 'Lewis et al., Meta AI',
    year: 2020,
    url: 'https://arxiv.org/abs/2005.11401',
    why: 'The paper that named RAG. Read it to see what the original architecture did and did not claim, before you build your own version of it this week.',
    minutes: 35,
  },
  {
    id: 'read-anthropic-contextual-retrieval',
    weekId: 'week-01',
    kind: 'post',
    title: 'Introducing Contextual Retrieval',
    source: 'Anthropic',
    year: 2024,
    url: 'https://www.anthropic.com/engineering/contextual-retrieval',
    why: 'Shows a concrete, production-tested fix for chunks that lose context, which directly informs how you design chunking in ms-rag-1 this week.',
    minutes: 25,
  },
  {
    id: 'read-api-claude-fable-5-1',
    weekId: 'week-01',
    kind: 'api',
    title: 'Claude Fable 5.1',
    source: 'Anthropic',
    year: 2026,
    url: 'https://www.anthropic.com/claude/fable',
    why: 'The current frontier model you will most likely generate with this month. Skim the model card for context limits and pricing before you pick a generator.',
    minutes: 10,
  },
  {
    id: 'read-api-gpt-6-astra',
    weekId: 'week-01',
    kind: 'api',
    title: 'GPT-6 Astra',
    source: 'OpenAI',
    year: 2026,
    url: 'https://openai.com/index/gpt-6-astra/',
    why: 'A second frontier option for the generator slot in your RAG stack this week. Compare its context window and pricing against Claude before you commit.',
    minutes: 10,
  },
  {
    id: 'read-api-gemini-3-8-flash',
    weekId: 'week-01',
    kind: 'api',
    title: 'Gemini 3.8 Flash',
    source: 'Google',
    year: 2026,
    url: 'https://blog.google/technology/ai/gemini-3-8-flash/',
    why: 'A cheap, fast option worth knowing about now, since ms-rag-3 later this month needs a low-cost model for query rewriting and reranking experiments.',
    minutes: 10,
  },

  // Week 2
  {
    id: 'read-lost-in-the-middle',
    weekId: 'week-02',
    kind: 'paper',
    title: 'Lost in the Middle: How Language Models Use Long Contexts',
    source: 'Liu et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2307.03172',
    why: 'Explains why stuffing more retrieved chunks into the prompt can hurt answer quality, which shapes how you order context in this week\'s hybrid retrieval work.',
    minutes: 35,
  },
  {
    id: 'read-bert-reranking',
    weekId: 'week-02',
    kind: 'paper',
    title: 'Passage Re-ranking with BERT',
    source: 'Nogueira and Cho',
    year: 2019,
    url: 'https://arxiv.org/abs/1901.04085',
    why: 'The original cross-encoder reranking recipe you are implementing this week in ms-rag-2, including why reranking beats retrieval scores alone.',
    minutes: 35,
  },

  // Week 3
  {
    id: 'read-ragas',
    weekId: 'week-03',
    kind: 'paper',
    title: 'RAGAS: Automated Evaluation of Retrieval Augmented Generation',
    source: 'Es et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2309.15217',
    why: 'Gives you the reference-free metrics for faithfulness and relevance you need this week to build the eval harness module in ms-rag-3.',
    minutes: 35,
  },
  {
    id: 'read-seven-failure-points',
    weekId: 'week-03',
    kind: 'paper',
    title: 'Seven Failure Points When Engineering a Retrieval Augmented Generation System',
    source: 'Barnett et al.',
    year: 2024,
    url: 'https://arxiv.org/abs/2401.05856',
    why: 'A field-tested taxonomy of what actually breaks in RAG systems, which you use this week to design the ablation cases for your eval harness.',
    minutes: 35,
  },

  // Week 4
  {
    id: 'read-prompt-injection',
    weekId: 'week-04',
    kind: 'paper',
    title: "Not What You've Signed Up For: Compromising Real-World LLM-Integrated Applications with Indirect Prompt Injection",
    source: 'Greshake et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2302.12173',
    why: 'Documents how instructions hidden in retrieved documents hijack an LLM, the exact threat model your guardrail layer in ms-rag-4 must defend against this week.',
    minutes: 35,
  },
  {
    id: 'read-self-rag',
    weekId: 'week-04',
    kind: 'paper',
    title: 'Self-RAG: Learning to Retrieve, Generate, and Critique through Self-Reflection',
    source: 'Asai et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2310.11511',
    why: 'Shows a model deciding when to retrieve and self-critiquing its answer, directly relevant to the RAG-vs-fine-tuning defense question you close month 1 with.',
    minutes: 35,
  },

  // Week 5
  {
    id: 'read-graphrag',
    weekId: 'week-05',
    kind: 'paper',
    title: 'From Local to Global: A Graph RAG Approach to Query-Focused Summarization',
    source: 'Edge et al., Microsoft',
    year: 2024,
    url: 'https://arxiv.org/abs/2404.16130',
    why: 'The design this month\'s advanced-RAG milestones build toward and month 3\'s project implements directly, so read it now to plan the adaptive retrieval work ahead.',
    minutes: 35,
  },
  {
    id: 'read-mteb',
    weekId: 'week-05',
    kind: 'paper',
    title: 'MTEB: Massive Text Embedding Benchmark',
    source: 'Muennighoff et al.',
    year: 2022,
    url: 'https://arxiv.org/abs/2210.07316',
    why: 'Gives you a principled way to pick an embedding model for the hierarchical chunk store you are building this week, instead of guessing.',
    minutes: 35,
  },
  {
    id: 'read-api-claude-opus-5',
    weekId: 'week-05',
    kind: 'api',
    title: 'Claude Opus 5 with the effort dial',
    source: 'Anthropic',
    year: 2026,
    url: 'https://www.anthropic.com/claude/opus',
    why: 'The effort dial changes the cost-quality tradeoff for the planner you are building this month, worth knowing before you wire up adaptive retrieval calls.',
    minutes: 10,
  },

  // Week 6
  {
    id: 'read-ir-book-bm25-eval',
    weekId: 'week-06',
    kind: 'post',
    title: 'Introduction to Information Retrieval: BM25 and evaluation chapters',
    source: 'Manning, Raghavan, and Schütze',
    year: 2008,
    url: 'https://nlp.stanford.edu/IR-book/',
    why: 'Grounds the BM25 half of your hybrid retriever and the evaluation metrics you are about to reuse for the router work this week, in first-principles detail.',
    minutes: 25,
  },
  {
    id: 'read-react',
    weekId: 'week-06',
    kind: 'paper',
    title: 'ReAct: Synergizing Reasoning and Acting in Language Models',
    source: 'Yao et al.',
    year: 2022,
    url: 'https://arxiv.org/abs/2210.03629',
    why: 'The reason-then-act loop underlies the structured/unstructured routing decision this week\'s milestone asks you to build.',
    minutes: 35,
  },
  {
    id: 'read-api-glm-5-3',
    weekId: 'week-06',
    kind: 'api',
    title: 'GLM-5.3',
    source: 'Z.AI',
    year: 2026,
    url: 'https://z.ai/blog/glm-5.3',
    why: 'A lower-cost alternative worth benchmarking for the router\'s cheap-path model this week, since routing decisions live or die on unit economics.',
    minutes: 10,
  },

  // Week 7
  {
    id: 'read-memgpt',
    weekId: 'week-07',
    kind: 'paper',
    title: 'MemGPT: Towards LLMs as Operating Systems',
    source: 'Packer et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2310.08560',
    why: 'Introduces the tiered-memory idea you need this week to decide what stays in context versus what gets paged out during red-team eval design.',
    minutes: 35,
  },
  {
    id: 'read-building-effective-agents',
    weekId: 'week-07',
    kind: 'post',
    title: 'Building Effective Agents',
    source: 'Anthropic',
    year: 2024,
    url: 'https://www.anthropic.com/engineering/building-effective-agents',
    why: 'Lays out workflow patterns (routing, orchestrator-workers) you will reuse directly in month 4\'s agent project, so read it now while the guardrail work is fresh.',
    minutes: 25,
  },
  {
    id: 'read-api-deepseek-v4-flash-vision',
    weekId: 'week-07',
    kind: 'api',
    title: 'DeepSeek V4 Flash Vision',
    source: 'DeepSeek',
    year: 2026,
    url: 'https://www.deepseek.com/en',
    why: 'Adds vision to a low-cost model line, relevant once your red-team eval set this week starts covering documents with embedded images.',
    minutes: 10,
  },

  // Week 8
  {
    id: 'read-prompt-report',
    weekId: 'week-08',
    kind: 'paper',
    title: 'The Prompt Report: A Systematic Survey of Prompting Techniques',
    source: 'Schulhoff et al.',
    year: 2024,
    url: 'https://arxiv.org/abs/2406.06608',
    why: 'A vocabulary and taxonomy for the prompting techniques your red-team eval set this week needs to probe systematically rather than ad hoc.',
    minutes: 35,
  },
  {
    id: 'read-chain-of-thought',
    weekId: 'week-08',
    kind: 'paper',
    title: 'Chain-of-Thought Prompting Elicits Reasoning in Large Language Models',
    source: 'Wei et al.',
    year: 2022,
    url: 'https://arxiv.org/abs/2201.11903',
    why: 'The reasoning technique your judge model can use to explain a faithfulness score, closing out month 2\'s guardrail eval report with clearer failure explanations.',
    minutes: 35,
  },
  {
    id: 'read-api-qwen-3-8',
    weekId: 'week-08',
    kind: 'api',
    title: 'Qwen 3.8',
    source: 'Alibaba',
    year: 2026,
    url: 'https://qwenlm.github.io/',
    why: 'Another open-weight option to benchmark for on-prem or cost-sensitive deployments of the month 2 project you are wrapping up this week.',
    minutes: 10,
  },

  // Week 9
  {
    id: 'read-lora',
    weekId: 'week-09',
    kind: 'paper',
    title: 'LoRA: Low-Rank Adaptation of Large Language Models',
    source: 'Hu et al.',
    year: 2021,
    url: 'https://arxiv.org/abs/2106.09685',
    why: 'The parameter-efficient fine-tuning method month 6\'s project is built around, worth understanding early since it recurs across the roadmap.',
    minutes: 35,
  },
  {
    id: 'read-qlora',
    weekId: 'week-09',
    kind: 'paper',
    title: 'QLoRA: Efficient Finetuning of Quantized LLMs',
    source: 'Dettmers et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2305.14314',
    why: 'Shows how quantization keeps fine-tuning affordable on a single GPU, the budget constraint the graph-RAG extraction pipeline this week has to respect too.',
    minutes: 35,
  },

  // Week 10
  {
    id: 'read-dpo',
    weekId: 'week-10',
    kind: 'paper',
    title: 'Direct Preference Optimization: Your Language Model is Secretly a Reward Model',
    source: 'Rafailov et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2305.18290',
    why: 'The preference-tuning method that replaces a separate reward model, which month 6 uses after SFT, so it pays to see the derivation before you need it.',
    minutes: 35,
  },
  {
    id: 'read-deepseek-r1',
    weekId: 'week-10',
    kind: 'paper',
    title: 'DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning',
    source: 'DeepSeek AI',
    year: 2025,
    url: 'https://arxiv.org/abs/2501.12948',
    why: 'Shows reinforcement learning producing reasoning behavior directly, a useful contrast to DPO while you plan the graph construction pipeline\'s quality checks this week.',
    minutes: 35,
  },

  // Week 11
  {
    id: 'read-chinchilla',
    weekId: 'week-11',
    kind: 'paper',
    title: 'Training Compute-Optimal Large Language Models',
    source: 'Hoffmann et al.',
    year: 2022,
    url: 'https://arxiv.org/abs/2203.15556',
    why: 'The compute-optimal scaling law that should inform how big a model you pick for community summarization in this week\'s graph-RAG milestone.',
    minutes: 35,
  },
  {
    id: 'read-attention-is-all-you-need',
    weekId: 'week-11',
    kind: 'paper',
    title: 'Attention Is All You Need',
    source: 'Vaswani et al.',
    year: 2017,
    url: 'https://arxiv.org/abs/1706.03762',
    why: 'The transformer architecture underlying every model you have used so far; re-read it now as a foundation for month 5\'s from-scratch build.',
    minutes: 35,
  },

  // Week 12
  {
    id: 'read-rope',
    weekId: 'week-12',
    kind: 'paper',
    title: 'RoFormer: Enhanced Transformer with Rotary Position Embedding',
    source: 'Su et al.',
    year: 2021,
    url: 'https://arxiv.org/abs/2104.09864',
    why: 'RoPE is one of the components month 5\'s GPT-from-scratch project swaps in and measures, so read the derivation before you implement it.',
    minutes: 35,
  },
  {
    id: 'read-gqa',
    weekId: 'week-12',
    kind: 'paper',
    title: 'GQA: Training Generalized Multi-Query Transformer Models from Multi-Head Checkpoints',
    source: 'Ainslie et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2305.13245',
    why: 'Explains the KV-cache savings from grouped-query attention, another component month 5 measures directly against a multi-head baseline.',
    minutes: 35,
  },

  // Week 13
  {
    id: 'read-flashattention',
    weekId: 'week-13',
    kind: 'paper',
    title: 'FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness',
    source: 'Dao et al.',
    year: 2022,
    url: 'https://arxiv.org/abs/2205.14135',
    why: 'The IO-aware attention kernel your training loop this week benefits from directly once sequence lengths grow past a toy size.',
    minutes: 35,
  },
  {
    id: 'read-vllm-pagedattention',
    weekId: 'week-13',
    kind: 'paper',
    title: 'Efficient Memory Management for Large Language Model Serving with PagedAttention',
    source: 'Kwon et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2309.06180',
    why: 'The KV-cache memory management scheme your streaming server milestone this month needs to understand before choosing a serving strategy.',
    minutes: 35,
  },

  // Week 14
  {
    id: 'read-speculative-decoding',
    weekId: 'week-14',
    kind: 'paper',
    title: 'Fast Inference from Transformers via Speculative Decoding',
    source: 'Leviathan et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2211.17192',
    why: 'A decode-time speedup technique directly applicable to the throughput numbers your streaming inference server needs to report this week.',
    minutes: 35,
  },
  {
    id: 'read-mt-bench-judge',
    weekId: 'week-14',
    kind: 'paper',
    title: 'Judging LLM-as-a-Judge with MT-Bench and Chatbot Arena',
    source: 'Zheng et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2306.05685',
    why: 'Documents the biases of LLM-as-judge scoring you should account for before trusting the comparative eval reports coming up in month 6.',
    minutes: 35,
  },

  // Week 15
  {
    id: 'read-swe-bench',
    weekId: 'week-15',
    kind: 'paper',
    title: 'SWE-bench: Can Language Models Resolve Real-World GitHub Issues?',
    source: 'Jimenez et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2310.06770',
    why: 'A benchmark design worth studying for how it grades task success on real, messy work, a pattern to borrow for your agent eval suite.',
    minutes: 35,
  },
  {
    id: 'read-ifeval',
    weekId: 'week-15',
    kind: 'paper',
    title: 'Instruction-Following Evaluation for Large Language Models (IFEval)',
    source: 'Zhou et al.',
    year: 2023,
    url: 'https://arxiv.org/abs/2311.07911',
    why: 'Gives you verifiable, rule-based instruction-following checks to add alongside the LLM-as-judge scores in your ongoing eval work.',
    minutes: 35,
  },

  // Week 16
  {
    id: 'read-scaling-laws',
    weekId: 'week-16',
    kind: 'paper',
    title: 'Scaling Laws for Neural Language Models',
    source: 'Kaplan et al.',
    year: 2020,
    url: 'https://arxiv.org/abs/2001.08361',
    why: 'The original scaling-law paper, useful context alongside Chinchilla for deciding how far to push model or data size in later fine-tuning experiments.',
    minutes: 35,
  },
  {
    id: 'read-lilian-weng-agents',
    weekId: 'week-16',
    kind: 'post',
    title: 'LLM Powered Autonomous Agents',
    source: 'Lilian Weng',
    year: 2023,
    url: 'https://lilianweng.github.io/posts/2023-06-23-agent/',
    why: 'A clear map of planning, memory, and tool-use components for agents, worth revisiting now as you approach month 4\'s multi-agent project.',
    minutes: 25,
  },

  // Week 17
  {
    id: 'read-eugene-yan-llm-patterns',
    weekId: 'week-17',
    kind: 'post',
    title: 'Patterns for Building LLM-based Systems and Products',
    source: 'Eugene Yan',
    year: 2023,
    url: 'https://eugeneyan.com/writing/llm-patterns/',
    why: 'A practitioner\'s checklist spanning evaluation, retrieval, fine-tuning, and guardrails that ties together everything the roadmap has covered so far.',
    minutes: 25,
  },
]
